### PR TITLE
Edit page button moved from app header to page

### LINKED ISSUE #643: iOS Safari: search bar changes shape when interacting with the page
In iOS Safari 16.0, the search bar has a strange behaviour and changes shape when interacting with the page.

Here is a screen recording:

`https://user-images.githubusercontent.com/14222414/201032306-dc172c9d-451a-48e3-9818-dbc129062a9b.mov`

### LINKED ISSUE #649: unclear logos on organizational page
On https://research-software-directory.org/organisations the eScience Center and Utrecht university have a green-ish checkmark (quite big) next to their name. Why is that?
Clicking on it, or mouse-hovering do not give me extra information.

### PR DESCRIPTION
**Pull request by dmijatovic**
# Resolve layout issues for mobile

Closes #643 
Closes #649

Changes proposed in this pull request:
* Edit page button is moved from app header to page itself. On mobile screen with low resolution (<400px) there was no sufficient space for all buttons in app header. Therefore I moved edit button to page itself.
* On edit page
   * the title color changed from primary to normal text
   * view page button created in the same "style" as the edit page button
   * image and caption info are "grouped" in order to be shown/hidden at the same time
* Layout of dropdowns in the app header and filter dropdown layout and behaviour is improved for smaller screens
* Added test for edit button
* Unrelated: added mouse-over text "Officially registered organisation" to checkmark logo on organisation page

How to test:
* `make start`
* login as rsd_admin to be able to edit software/projects
* navigate to software you can edit, it should display Edit page button (see screenshot 1)
* navigate to project you can edit, it should display Edit page button (see screenshot 2)
* The edit page button in changed to be in the same still too (see screenshot 3)

## 1a. Example edit page button on the software page (desktop)
image

## 1b. Example edit page button on the software page (mobile)
image

## 2a. Example edit page button on the project page (tablet)
image

## 2b. Example edit page button on the project page (mobile)

image

## 3. Example view page button

image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests

### CODE REVIEW

**Comment by cmeessen** [comment]
The random switching still happens

**Review by ewan-escience — CHANGES_REQUESTED** [review]
Works nicely, and I don't experience the weird search bar behaviour on Firefox. One request, could you change the view page and edit page buttons to use `a` tags?

**Comment by dmijatovic** [comment]
> Works nicely, and I don't experience the weird search bar behaviour on Firefox. One request, could you change the view page and edit page buttons to use `a` tags?

@ewan-escience I prefer to leave it as it is because user should have JS enabled at this point (already authenticated). We use SPA router to perform page change without reloading complete page (smoother experience).

**Comment by ewan-escience** [comment]
But we use `a` tags everywhere without full page reloads. And people might want to open the view/edit page in a different tab.

**Comment by cmeessen** [comment]
The search bar on iOS is fixed now :+1:

**Review by cmeessen — APPROVED** [review]

**Pull request merged**
