### PR TITLE
105 software information middle

### LINKED ISSUE #105: Add software - Software information - middle section
# Software information

This section provides basic information and contains 2 sections: middle and right side section.

## Implement middle section parts

- Title and Short description should already be populated from the add software modal. 
- Project URLs are not mandatory
- Description is text-area, supporting markdown and enabling an preview.

▶ Recources and Ideas - RSD

### PR DESCRIPTION
**Pull request by dmijatovic**
# Add/Edit software - Software information - middle section

Closes #105 

Changes proposed in this pull request:
*  Some improvements in the layout and font choice (Roboto is set to first place to closely resemble legacy layout)
*  Middle section of the software information step (see design below).

How to test:

*  `docker-compose down --volumes`: remove older version of database. This PR implements two changes in the database, add new columns to software table and additional view
* `docker-compose up`: it should build database and frontend images (new versions) and create database with new structure 
* Run data-migration again
```bash
# navigate to data-migration folder
cd data-migration
# run data migration
docker-compose up
```
* You are NOT able to add or edit software if you are not signed in. You will see simple 401 message if you try to edit Xenon for example using [edit url](http://localhost/software/xenon/edit)
* Login with SURF using Test IsP and user professor1
* You are NOT able to edit software if you are not maintaining it. For example [Xenon](http://localhost/software/xenon/edit). Currently you will see simple 403 message. Note! Legacy software does not have maintainers assigned to it. When creating new software you are assigned as maintainer (owner) of that software.
* Create new software, using + button at the top right of the screen. After saving you will be redirected to edit page. 
* Provide additional information about software, URL's and markdown. **Check labels on spelling and clarity.** It is possible to use remote markdown file. The content will be loaded in the preview (see image).

image

* Save changes. You will get notification about success or failure.
* Currently you can only view new software manually, as "published" state is not covered yet. To view software manually use url without "edit" segment, for example: for Xenon **edit url** is `http://localhost/software/xenon/edit` and **view url** is `http://localhost/software/xenon`. 
* Software page is updated to load `remote markdown` files too
* Notification about "unsaved" changes. If you navigate to next section of edit without saving shanges you will get simple notification about it. Further improvements of this feature are needed in order to navigating away from edit section or reloading the page

PR Checklist:

*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by ctwhome** [comment]
Thanks for the hard work. I would add a few comments to the PR: 

1.  I wouldn't use the New markdown as a title for the custom description since the description is something custom, but not necessarily 'new' every time the software page is edited. In fact, the custom description is never new, is either empty or filled.
2.  Another point, maybe is good to validate the URL fo the external MD file, to be sure that only markdown files can be accepted
3.  I would add a small tooltip with the info icon to explain what possibilities are by linking your external MD: for example, we can say that it is always up to date and whenever the original file changes, it will be reflected on the software page. 
4.  I would remove the word users inside the title: "What {title} can do for you?"

**Review by ewan-escience — APPROVED** [review]
Nice work!

**Comment by jmaassen** [comment]
When trying to import a remote markdown file, I get a "500 NetworkError when attempting to fetch resource". Not sure why...

network

**Review by jmaassen — APPROVED** [review]
Looks good! I did have trouble importing a remote markdown though...

**Comment by dmijatovic** [comment]
>

**Pull request merged**
