### PR TITLE
Calculate distance between left an centered container

### LINKED ISSUE #916: Position correctly the highlights card on window resize
The current carousel only uses CSS for the complete iteration. However, it is impossible to calculate the distance between the first highlighted card with the left side of the content, which is centered and responsive, only with css.

In this task, i will add the necessary react code to calculate the distance and apply it to the scroll position of the carrousel.

See working example here: https://www.apple.com/store

image

### PR DESCRIPTION
**Pull request by ctwhome**
Fixes #916

Changes proposed in this pull request:

*      fix distance cards
distance

How to test:

*

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by dmijatovic — APPROVED** [review]
Nice work!

**Comment by jmaassen** [comment]
Works well, but I do notice that the rightmost highlight does not align yet? See image below. I cannot scroll further right at this point.

Screenshot 2023-06-22 at 11-13-45 Software Research Software Directory

**Comment by ctwhome** [comment]
> Works well, but I do notice that the rightmost highlight does not align yet? See image below. I cannot scroll further right at this point.
> 
> Screenshot 2023-06-22 at 11-13-45 Software Research Software Directory
> 
> The leftmost aligns nicely:
> 
> Screenshot 2023-06-22 at 11-13-38 Software Research Software Directory

oh ya indeed, I only did it for the left one, which is the one who shows always

**Comment by dmijatovic** [comment]
Can we merge this for now and come back later if additional improvements are needed? I would like to merge this PR in rsd-v2-release and then rebase it to main (as we made new release).

**Pull request merged**
