### PR TITLE
News section

### LINKED ISSUE #1059: Add news items section to front page.
In our discussion with comms, we concluded that it would make sense to also add a news section to the RSD site. This would allow us to communicate with users and stakeholders without the need for a mailing list or newsletter (which we still intent to do, however). 

There are several ways to do this, some examples:

- Top X on front page, linking to individual news pages:  [escience center](https://www.esciencecenter.nl/), [nwo](https://www.nwo.nl/), [lcrdm](https://lcrdm.nl/), [orcid](https://orcid.org/), [datacite](https://datacite.org/), [crossref](https://www.crossref.org/)
- Separate blog:  [zenodo](https://blog.zenodo.org/), [docusaurus](https://docusaurus.io/blog)

The difference between news and blog seems a bit blurred judging from these examples.

### PR DESCRIPTION
**Pull request by dmijatovic**
# News - admin section

**This is admin section of news. I still need to create view section on the home page.**

Closes #1059 

Changes proposed in this pull request:
* Added news edit section 
* News overview section with grid/list layout and add button for admins
* View/Edit menu button in the card and list item for admins 
* Included publishing date in the news url and as unique key (slug+publishing date)
* Increased size of image in the list item (shared component, it impacts all overviews)
* Fix invisible button border for the homepage buttons on firefox
* Added latest 3 news items to homepage incl. the button to news overview
* Added support for multiple images per news item
* Added news section in the documentation to administration chapter.

How to test:
* `make start` to build app
* login as rsd admin
* use + button at the top right and select "Add news" option (rsd-admin only)
* create new news item and upload few images
* try copy link and add image somewhere in the markdown
* publish news item, it will be shown in the news overview
* edit news article
* delete one of the images and confirm that link is removed from markdown
* delete news article
* validate that only published articles are shown on public page. Unpublish an article and logout. Confirm that article is not listed.
* in the user menu navigate to news section (rsd-admin role only)

## News menu option (for admins)

image

## Create news item
image

## News items overview with add news button (for admins)
image

## Edit news item
image

## News article
image

## Latest news on homepage
image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by jmaassen** [comment]
With the current setup, we cannot have more that one image per item. While this is probably fine for now, I think I remember we discussed the option to have both a "cover image" and "additional images" which could then be used in the markdown in any order using the "copy link" option?

**Comment by jmaassen** [comment]
The current 'full width' approach to news items doesn't improve the layout. 

For example, take this NWO nieuws item: 

Screenshot 2024-03-25 at 16-18-37 NWO heeft acht aanvragen toegewezen voor Rekentijd op de Nationale Computersystemen NWO

For us, the same image and text would give us: 

Screenshot 2024-03-25 at 16-19-02 NWO heeft acht aanvragen toegewezen voor Rekentijd op de Nationale Computersystemen Research Software Directory

Maybe it would be better to reduce the width of the news items to a certain size? This would also prevent the image from blowing up to more that full screen size.

**Comment by dmijatovic** [comment]
Thanks for the feedback. I made changes, the PR is ready for next review round :-)

**Comment by jmaassen** [comment]
Big improvement in the look and feel of the finished news items! For comparison, this is the "NWO" item I used in the previous comment: 

Screenshot 2024-03-27 at 10-52-09 NWO heeft acht aanvragen toegewezen voor Rekentijd op de Nationale Computersystemen Research Software Directory

Some further comments: 

The font of the title is somewhat big on the news page. It may be better to reduce it to the size that the subtitle has now (or something in between?). In turn, the subtitle could be a bit smaller, or maybe only a bold version of regular text?Example: 

Screenshot 2024-03-27 at 10-52-42 News item 2 Research Software Directory

(more later)

**Comment by jmaassen** [comment]
Second point: change the subtitle to card summary

**Comment by dmijatovic** [comment]
@jmaassen I made requested changes.

**Comment by jmaassen** [comment]
Works great! Adding multiple images works well, and the narrower news items are easier to read.

**Review by jmaassen — APPROVED** [review]

**Review by cmeessen — APPROVED** [review]
Very nice, works like a charm :+1:

**Pull request merged**
