### PR TITLE
285 user profile organisations

### LINKED ISSUE #125: Separate the context of the login menu
The buttons Log out stay at the same level as seeing your repositories and organization. 

I suggest moving the sign-out button into its own section as shown here:

As an extra: Github shows the user name in the same floating menu, probably a good idea for us since the majority of the people may use working accounts, so it is good to make it clear

### LINKED ISSUE #279: Profile Page
- [x] Scaffold sections #281
- [x] Software section #282 
- [x] Projects section #283 
- [ ] Profile #284 
- [ ] Organisations #285

### LINKED ISSUE #284: User profile - personal info
Show personal information of logged in user. Current info shown on the page is extracted from the token. Additional info is available in the `login_for_account` table.

- There is no design for this section. 
- Create api call to login_for_account using postgrest
- Show, name, email and home_organisation information of the user

For now we should only show the user information: name, email, organisation. This information originates from the login provider (IdP) and I am not sure if we shold let user change it.  For later we can enable adding additional emails, maybe upload the image. 

**I think we should discuss these options.**

## Starting position

image

### LINKED ISSUE #285: User profile - organisations
Show list of organisations the user is maintainer of. Use rpc created for this purpose `organisations_by_maintainer`. The approach should be similar to software and project sections. You could use same organisation cards as on the organisations page

**Note! You need to filter on maintainer and primary_maintainer props**
The organization, in contrast to software and project has primary maintainer in addition to "normal" maintainers. Applying "or" clause in postgrest api can be found in the [documentation](https://postgrest.org/en/v9.0/api.html?highlight=filter#horizontal-filtering-rows).

## Stating position
image

## Desired outcome (draft)

image

### PR DESCRIPTION
**Pull request by ruester**
# Add organisations overview for user page

Fixes #285
Closes #284 
Closes #125 
Closes #279

Changes proposed in this pull request:

* add the list of organisations to the user page
* show basic profile information: account id, name and role
* separated logout from other menu items and menu items extended to my software, my projects, my organisations

How to test:
* create software entries with organisations
* go to the user page and click on organisations

# Example 

image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [X] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by ruester** [comment]
@dmijatovic I cannot get the `organisations_by_maintainer` working, I also tried on the DB directly but this view was empty... It may has something to do with the `maintainer_for_organisation` table.. I tried it with a LEFT JOIN and the results were not empty anymore and I also added the count columns in order to get the `OrganisationsGrid` working, but don't know if this right (otherwise we would need a new component?)..
But if I want to filter on `maintainer_for_organisation` with `WHERE maintainer_for_organisation.maintainer = maintainer_id` there are no results again (which is what I expect since the join cannot be fulfilled)..

```sql
rsd-db=# SELECT
rsd-db-# o.id,
rsd-db-# o.slug,
rsd-db-# o.parent,
rsd-db-# o.primary_maintainer,
rsd-db-# o.name,
rsd-db-# o.ror_id,
rsd-db-# o.website,
rsd-db-# o.is_tenant,
rsd-db-# logo_for_organisation.id AS logo_id,
rsd-db-# software_count_by_organisation.software_cnt,
rsd-db-# project_count_by_organisation.project_cnt,
rsd-db-# children_count_by_organisation.children_cnt
rsd-db-# FROM
rsd-db-# organisation AS o
rsd-db-# LEFT JOIN
rsd-db-# logo_for_organisation ON o.id = logo_for_organisation.id
rsd-db-# LEFT JOIN
rsd-db-# software_count_by_organisation() ON software_count_by_organisation.organisation = o.id
rsd-db-# LEFT JOIN
rsd-db-# project_count_by_organisation() ON project_count_by_organisation.organisation = o.id
rsd-db-# LEFT JOIN
rsd-db-# children_count_by_organisation() ON o.id = children_count_by_organisation.parent
rsd-db-# LEFT JOIN
rsd-db-# maintainer_for_organisation ON o.id = maintainer_for_organisation.organisation;
                  id                  |                                slug                                 | parent |          primary_maintainer          |                                 name                                  |          ror_id           |              
website               | is_tenant | logo_id | software_cnt | project_cnt | children_cnt 
--------------------------------------+---------------------------------------------------------------------+--------+--------------------------------------+-----------------------------------------------------------------------+---------------------------+--------------
----------------------+-----------+---------+--------------+-------------+--------------
 94b00a7a-ab67-4d7c-a221-fb4feb492707 | max-planck-society                                                  |        | 01a93d43-3000-418f-8fb7-a7640b6deb99 | Max Planck Society                                                    | https://ror.org/01hhn8329 | http://www.mp
g.de/en               | f         |         |            1 |             |             
 cd521114-d9ca-410f-b38a-eb0d2f334246 | helmholtz-centre-potsdam-gfz-german-research-centre-for-geosciences |        | 01a93d43-3000-418f-8fb7-a7640b6deb99 | Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences | https://ror.org/04z8jg394 | http://www.gf
z-potsdam.de/en/home/ | f         |         |            1 |             |             
(2 rows)
```

```sql
rsd-db=# select * from maintainer_for_organisation;
 maintainer | organisation 
------------+--------------
(0 rows)
```

At which point to we want to solve this issue? Changing `maintainer_for_organisation` or `organisations_by_maintainer` or else?

**Comment by dmijatovic** [comment]
@ruester Thanks for the assistance on this issue. The query you created is quite good. I made only one minor improvement in the WHERE I also included primary_maintainer. For organisation we have two type of maintainers: primary_maintainer (in organisation table) and other maintainers (same as with software and projects). I made improvement but I also did few more "quick" issues here.

**Comment by ruester** [comment]
@dmijatovic many thanks for fixing the SQL function! I tested it and it works now as expected :+1: 
thats also a good improvement for the user icon drop down menu, great! :wink:

**Review by ewan-escience — APPROVED** [review]

**Review by ctwhome — APPROVED** [review]
good job, and really nice to see the login button list is also now reorganized with the logout option at the bottom

**Pull request merged**
