### PR TITLE
Bulk import / Import publications

### PR DESCRIPTION
**Pull request by dmijatovic**
# Import publications (software and projects)

Changes proposed in this pull request:
* Bulk import button is renamed to Import publications section and set at the second position
* This section is used on edit software/mentions, project/input and project/output pages
* The max number of items is set to 50 and the validation on row count is implemented
* Wait cursor during validation is implemented
* Validation on already included publication is implemented
* Info text on software/mention, project/impact en project/output pages are updated.

How to test:
* `make start` to rebuild
* use DOI input examples from #808 
* Try to import same list twice in the same software/project. You should get respose from validation report that the entries are already in the software/project
* Validate text changes in info boxes

## Position of section and the information (Software mentions)
image

## Position of section and the information (Project impact)
image

## Position of section and the information (Project output)
image

## Input DOI modal
image

## Selection and validation modal
image

## New manual item
image

PR Checklist:
*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by ctwhome** [comment]
This is a new design. All suggestions and changes are indicated in the design.

**Comment by dmijatovic** [comment]
@ctwhome Thanks for the suggestions. Proposed design impacts shared components used in this section. These are used on lot of places in software and project edit sections. All search inputs use the same component. I have created additional issue #824 where we can define some basic design tokens, apply and then examine the impact of the change. Let's discuss next steps during the standup.

**Comment by jmaassen** [comment]
Maybe "add a research output" would be a suitable replacement for "Add mention", "Add output" and "Add impact"? That way we can use the same text on all three tabs. The "mention", "impact" and "output" title at the top should be enough to indicate in which tab you're adding stuff.

**Comment by dmijatovic** [comment]
@jmaassen and @ctwhome. I have further look into suggested design changes. I can adjust the layout to the approach created in the images below. I wonder if we need to adjust search design on the other pages like contributors, team members and organisations pages. At this moment I would leave the searchbox design to be same as in other pages.

## Edit software mentions page
image

## Edit project impact page
image

## Edit project output page
image

**Review by ctwhome — APPROVED** [review]
Amazing work it looks fantastic!

**Comment by ctwhome** [comment]
as a small remark. The text can be improved a bit more.

**Comment by dmijatovic** [comment]
@jmaassen Can you approve this PR please?

**Pull request merged**
