### PR TITLE
Include Roboto fonts to default index.css

### PR DESCRIPTION
**Pull request by dmijatovic**
# Include Roboto and Work Sans fonts into default index.css and the font woff2 files

Changes proposed in this pull request:

* The fonts defined in default styles of RSD include Roboto font. For the users who do not have Roboto fonts locally the organisation card is not shown with proper font and font-weight.      
* The font files are placed in the `frontend/public/styles` folder. This folder is part of docker-compose volume mounts and can be overwritten by custom settings.

How to test:

* `make start` to rebuild everything
* confirm Roboto font is included by navigating to organisation overview, the score fonts should look like in the screenshot

## Example Roboto font applied

image

image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by ewan-escience — APPROVED** [review]
Looks good, let's wait until we have discussed licensing before merging though.

**Review by cmeessen — APPROVED** [review]
The font is included for your version.

Unfortunately, also because of the very long titles of some of our research centres, the layout in the HIFIS version is now quite off:

image

But this can be addressed later.

**Comment by dmijatovic** [comment]
@cmeessen I think we should reduce the title to max of two lines. Currently the max. is set to 3 lines but that seem to be too much for the organisation card.

**Comment by dmijatovic** [comment]
After disusing the problem, we decided to create new PR with following changes: 
- Font size: 3.5rem
- Font weight: 200
- image objectFit: contain (to always show complete logo)

**Review by jmaassen — APPROVED** [review]
Works as expected

**Pull request merged**
