### PR TITLE
feat: migrate user documentation to main repo

### LINKED ISSUE #911: Suggestion: migrate user documentation to this repo
We would like to suggest to migrate [research-software-directory/documentation](https://github.com/research-software-directory/documentation) to this repository.

We think that this could have some benefits, e.g.

- the RSD repo always comes with the current user documentation
- keeping the user documentation in sync with the RSD might become easier since no additional pull request has to be created if we want to update the documentation together with a feature update/bug fix

Apart from this, there are several issues updating the dependencies of the documentation. But this might have to go into a new issue.

### PR DESCRIPTION
**Pull request by dmijatovic**
# Migrate user documentation to main repo

**This is the first attempt. I do expect some feedback at least from @jmaassen and @cmeessen** :-)

Closes #911

### Changes proposed in this pull request:
* Move the content of users documentation from documentation repo to main RSD repo into the folder documentation
* Setup Docusaurus in the `\documentation` folder
* Added `maintaining organisation` page contributed by Hellmholtz. The content is slightly adjusted and the images are updated to v2
* (Proposal) Created 4 sections in the documentation:
    * User manual: documentation for RSD users and maintainers
    * API services: postgREST api and OAI-PMH description
    * RSD administration: section about running RSD instance and RSD administration pages
    * Contribute to RSD: this section is for contributors and contains information relevant for the contributors
* Add `documentation` service to main docker-compose.yml and to docker-compose.yml in the deployment folder. 
* Extend release action to create the documentation image using the same version as the rest of RSD services

### To do
- `Last changed date` info at the right bottom corner of the page is not working when building documentation as a  Docker image because Git information is not available during the build. If this feature is desired we would need to further investigate how to include git information without copying complete RSD project into Docker image.

### How to test:
* `make start` to build all services locally
* navigate to home page and start checking documentation links:
   * "Sing up to contribute" button has documentation link at the top of the modal
   * "Register your organisation" button has documentation link at the top of the modal
   * "Demo" button should open documentation at demo page
   * "Docs" button should open intro page of documentation
   * "FAQ" button should open FAQ section of user documentation
* check the documentation links in the footer section of RSD home page
* documentation app: view README.md file in the root of the documentation folder. It describes how to work with the current setup. Try running documentation locally and making changes.

## Example
image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by cmeessen** [comment]
Looking good :+1: I wonder whether there might be some confusion about the "Developer" and "Contributors" sections, partly because there is the term "Contributors" in the RSD, and partly because a contributor to the code is likely also a developer. I'd like to suggest this structure:

```
- User Documentation
- Technical Documentation
  - Contribution guidelines
    - Code of conduct
    - ..
  - Developer documentation
    - Getting started
    - ...
```

**Comment by dmijatovic** [comment]
@cmeessen, @jmaassen Let's think further about improving main sections. I do see tree separate sections at the top:
- Users documentation: this seem to be clear. 
- RSD Contributors (developers): this is section where we explain how RSD repo works, what we use and other technical info relevant to (new) contributors/developers that want to contribute to RSD source code. This section should include code of conduct too.
- Developers/System administrators: this section contains instructions for running an RSD instance, explaining the configuration file(s) and other relevant topics for running RSD instance. Other subsection in this section for RSD REST API (link to swagger, tables map etc). Then one section for OAI-PMH service we have and integration with OpenAIRE. High likely we will also have additional service using codemeta.json in the furutre.

I think that all mentioned topics could be placed in 3 different root sections based on the target audience: RSD users, RSD developers, Other developers using RSD API services. But maybe we need more sections at the top level and menu entries in the header?

**Review by jmaassen — DISMISSED** [review]
Looks good, but the naming of the chapters is still a bit ambiguous. I would go for: 

- User Manual
- API endpoints
- Hosting your own RSD
- Contributing to RSD Development
 
In addition (for a later PR), I would suggest splitting the User Documentation into a part for visitors (browsing the RSD), and a part for maintainers. We could call that latter part "Adding content to the RSD"?

**Comment by dmijatovic** [comment]
@jmaassen Thanks for the feedback. We are facing some layout limitation concerning the length of the menu titles in the header and menu options in the left side panel.  I have examined responsive layout definitions. It has a breakpoint set at 996px. I would like to propose the following approach. Please see the screenshot below as example

- The title of the website should be reduced to RSD
- The menu option for user manual should be reduced to "Users". The left panel title can be "User Manual"
- The menu option for API endpoints should reduced to "API". The left panel title can be "API endpoints"
- The menu option for Hosting your own RSD should be reduced to "Hosting". The left panel title can be "Hosting your own RSD"
- The menu option for Contributing to RSD Development seem to be too long for the menus and breaks into 2 lines. I suggest to "Contributors" in the header and "Contributing to RSD" in the left

## Responsive layout at 1024px width (Tablet)

image

**Review by ewan-escience — APPROVED** [review]
Looks good, nice work!

Since this PR is mainly focused on merging the two documentation sites into one and to switch to Docusaurus, we can add more content later on.

**Pull request merged**
