### PR TITLE
Added real organization logos to data-generation set

### PR DESCRIPTION
**Pull request by jmaassen**
Links to #913 (doesn't fix)

Changes proposed in this pull request:

*     added real organization logos and their license to the data generation dataset. 

How to test:

*  have a look in the data-generation/logos directory. Each logo file should be usable and have an associated license file containing a source link and license identifier.

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [X ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by dmijatovic** [comment]
Lokos good! @ewan-escience Should we also update data generation script in this PR?

**Review by dmijatovic — APPROVED** [review]

**Comment by ewan-escience** [comment]
Yes, I will update the script in this PR.

**Comment by dmijatovic** [comment]
Organisation logos looks good! Maybe add few software logos too?

**Comment by jmaassen** [comment]
I'll add additional logos for software.

**Pull request merged**
