### PR TITLE
1212 categories for communities

### PR DESCRIPTION
**Pull request by ewan-escience**
## Categories for communities, interface for creating and updating categories

Changes proposed in this pull request:

* Reorder database initialisation files to allow categories for communities
* Added size limits on various category columns
* Add frontend interface for admins to maintain global categories
* Add frontend interface for maintainers of a community to maintain their categories
* The data generation module now creates categories

How to test:

* Make sure to have communities enabled
* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale data-generation=1`
* Sign in as admin
* Go to the admin pages -> categories
* Play around with the categories (create new, edit, delete)
* Invite a maintainer for a community, sign in with that account
* Play around with the categories (create new, edit, delete) on the community page
* **Important:** check in the SQL files that nothing got lost unintentionally

**Todo in this PR**:

* [x] On the software edit page, only show global categories

**Todo:**

* Allow icons to be added to categories (see #975)
* Force software page maintainer to add categories when they want to join a community (see #1212)

Related to #1216

Related to #1212

Related to #1141

Related to #992

Related to #975

PR Checklist:

* [ ] Increase version numbers in `docker-compose.yml`
* [x] Link to a GitHub issue
* [x] Update documentation
* [ ] Tests

### CODE REVIEW

**Comment by ewan-escience** [comment]
@fembau can you to do the open point in the PR description?

**Comment by jmaassen** [comment]
For me the categories connected to a community are not saved? When I add some and reload, they are gone again...

**Comment by ewan-escience** [comment]
> For me the categories connected to a community are not saved? When I add some and reload, they are gone again...

Good catch, I forgot to attach those categories to the community, so they were saved as global categories instead. It should be fixed now.

**Review by jmaassen — APPROVED** [review]
Works as expected.

**Pull request merged**
