### PR TITLE
274 mentions

### LINKED ISSUE #196: Edit Project Page
# Edit project page

The user should be able to edit project if he/she is maintainer of it. The main idea is based on edit software approach. The user can create an project with a minimum information (title and subtitle) and then is forwarded to more extensive edit page that covers all aspects. 

The design of software edit page can be used as basis but the project edit page will have their own distinct sections:
- Project information (title,subtitle,description,links,tags and technologies) #242 
- Team (similar to contributors section on edit software page)
- Organisations (similar to organisations section on edit software page)
- Output: similar to mentions section on edit software page
- Impact: similar to mentions section on edit software page
- Related projects: similar to related software section on edit software page 
- Related software: similar to related software section on edit software page 
- Maintainers: add, invite maintainer(s)

Some of the sections can be "borrowed" from edit software page.

image

# Desired metadata for 'Projects' (feedback from PM meeting)

A project needs:
 * Title (1 short sentence)
 * Subtitle (optional, 1 sentence)
 * Start and End (possibly rounded to years: 2020 - 2024)
 * Abstract (optional, alinea)
 * Labels:
     * research domain: one or more out of: 3 (NWO), 50? (NWO https://www.nwo.nl/en/nwo-research-fields ), 4 (NLeSC) or many (Elsevier?), EU approved list?, ORCID list?
         * OPTION: make this a custom static set per organization? would make search more difficult
         * OPTION: make this a fixed list, but short (~10s)
     * eScience expertise used between 3 and 5 out of (list of 5 expertises techleads?). 
         * OPTION: free keywords seem most suitable to me (Dusan) 
 * Project Output
     * github repos (ie. software)
     * publications?
     * mentions / free form ~1 alinea of text + URLs to fi. a press release or quote?
 * related organizations: zero to many
 * involved persons with roles:
     * contact persons (one)
     * project leaders (one or more)
     * project collaborators (zero or more)
* Project funding
    * funding organizations: at least one, possibly many
    * Grant ID: one id per project (maybe link to more info)    
* Project links
   * call CFP (Call For Proposal): link
   * other links free to add many as user needs

### LINKED ISSUE #274: Mentions - edit project & edit software
# Creating mentions using DOI

The legacy RSD scrapes mentions from Zotero and makes them available in the mentions section of the software. When working with multiple clients this approach is less suitable because not every client uses Zotero as reference manager. 

## Manual adding of mention

The first suggestion received from potential users is that one should be able to add mention based on DOI, for publications and for other type of mention (that do not have DOI/ISBN) like blogs or web articles by simply creating a new entry and providing required information (type, title, url, source?) and optional information (image url, author, is_featured, date). 

- Legacy table
```sql
CREATE TABLE mention (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	author VARCHAR,
	date TIMESTAMP,
	image VARCHAR,
	is_featured BOOLEAN DEFAULT FALSE NOT NULL,
	title VARCHAR NOT NULL,
	type mention_type NOT NULL,
	url VARCHAR,
	-- version INTEGER,
	-- zotero_key VARCHAR UNIQUE NOT NULL,
	-- scraped_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);
```
- New mentions table structure
```sql
CREATE TABLE mention (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        doi VARCHAR(255) UNIQUE,
	url VARCHAR(500) UNIQUE,
	title VARCHAR(500) NOT NULL,
	authors VARCHAR(1000),
	publisher VARCHAR(255),
	publication_year VARCHAR(4),
	image_url VARCHAR(500),
	is_featured BOOLEAN DEFAULT FALSE NOT NULL,
	mention_type mention_type NOT NULL,
        source VARCHAR(50) NOT NULL,
        version INTEGER,
	zotero_key VARCHAR UNIQUE,
	scraped_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);
```

### Mention types

Legacy RSD has following mention types (incl. count of items in the table). This is fixed list based on enum. Maybe we should make it bit more flexible by creating mention_type table so the list can be easier extended then using enum?

- attachment (0 items) [REMOVE]
- blogPost (104 items)
- book (9 items)
- bookSection (23 items)
- computerProgram (275 items)
- conferencePaper (186 items)
- document (35 items) ->OTHER
- dataset [ADD]
- interview (4 items)
- journalArticle (598 items)
- magazineArticle (10 items)
- manuscript (9 items) -> OTHER
- newspaperArticle (8 items)
- note (0 items) [REMOVE]
- presentation (402 items)
- radioBroadcast (1 item) -> OTHER
- report (42 items)
- thesis (16 items)
- videoRecording (39 items)
- webpage (58 items)
- other [ADD]

### Zotero example

Looking at the [Zotero manual](https://www.zotero.org/support/adding_items_to_zotero) they seem to support adding refference items from different sources on demand (see image below for reference or use link).

image

[From discussion](https://github.com/research-software-directory/RSD-as-a-service/discussions/266)

## Crossref REST API documentation

I find readme on the [Crossref REST API repo](https://github.com/CrossRef/rest-api-doc/) good starting point. Note that this documenation is deprecated. The REST API is recently migrated to ElasticSearch backend. New version of [API documentation is available in swagger format](https://api.crossref.org/swagger-ui/index.html)

## Crossref API example

https://api.crossref.org/works/10.1007/978-3-319-92016-0_13

## DataCite
The [api documentation of datacite can be foud here](https://support.datacite.org/docs/api) for REST API.
They also offer [GraphQL version of API](https://support.datacite.org/docs/datacite-graphql-api-guide). I currently decided to use GraphQL version to query limited amount of properties. The [GraphiQL interface is available here](https://api.datacite.org/graphql)

### Datacite query example

https://api.datacite.org/works?query=10.5281/zenodo.5592607

### LINKED ISSUE #300: Adding mentions from DataCite/CrossRef using publication titles: sort output by best match
This issue refers to the features implemented with #295.

When adding a mention by searching for the title of a publication in DataCite/CrossRef, the list that is shown does not always put the best fitting result at the top of the list.

For example, searching for "The thermal and rheological state of the Northern Argentinian foreland basins" will place the object with this title somewhere in the middle.

Sorting by the best matching result (maybe the edit-distance may be useful here?) would help the user to more quickly find the desired result.

/cc @dmijatovic

### PR DESCRIPTION
**Pull request by dmijatovic**
# Mentions, Impact and Output

Closes #274 
Closes #196 
Closes #300 

Changes proposed in this pull request:
*  Software edit mention section is updated to import mentions based on DOI or search for publications in crossref and datacite
*  Software view, mention section is updated to include additional information like publisher, page, authors and DOI
*  Project edit impact and output sections are implemented in the similar way as mentions in the software section
*  Project view, impact and output section are updated to include additional information (publisher, page, authors and DOI)
*  Software and project share mention components which are moved into separate folder under components

**This is quite large PR, I want to suggest to handle only errors, if any, in this PR and create new issues for any desired improvements.**

How to test:

* `docker-compose down --volumes` to remove old version
* `docker-compose build` to build solution
* `docker-compose up` to start
*  run data-migration service (cd data-migration && docker-compose up)
*  login with some user, professor1 for example
*  create new software
*  add mentions to software:
     *  use add button to manually create mention
     *  use an DOI, for example 10.1007/978-3-642-11274-4_996
     *  use title to find an publication, for example Struggling Tigers: the Asian financial crisis
     *  use add button to create another mention, this time provide an image and select is featured flag, use for example this image 
*  save software and preview (picture 1)
*  create new project
*  add impact use similar approach as with mentions for software
*  add output, use similar approach as with mentions for software 
*  save project and preview (picture 2)

## Advanced tests
For these tests you will need to manually change some information in the database

* make yourself maintainer of the software and projects
* edit existing software, for items that have DOI and are on "manual" source (this is default by migration) you can edit these or update item using DOI. Note! After updating item from DOI this mention cannot be edited more. In addition, the mention might be placed into a different category due to information extracted from DOI. Some improvements might be needed

## Example software mentions view
image

## Example project impact and output view
image

## Example editing section
image

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by cmeessen — APPROVED** [review]
Very impressive, this is working really well.

There are a couple of comments/suggestion that I have. Some requested changes are rather small (see inline comments). For the ones below I will create new issues and add references soon:

1) One can only create a featured mention if the a URL is provided. Adding mentions leaves a lot of decisions to the users, e.g. only title and type are required, so I would think that the URL would be optional as well. If you would like to keep this constraint, maybe a comment about what is required for a featured mention may be helpful, because the user may be puzzled as to why they cannot feature a mention (see #297).

2) Imported mentions cannot be edited and thus not be featured, which is a pity.

3) In the "Create new item" window, I accidentally missed the Save button and clicked on the greyed out background. All my values that I typed into the text field were lost afterwards. For the user it would make it a bit easier if the entries would be preserved (see #299).

4) Searching for a publication title may not show the best fitting result at the top of the list. For example, try "The thermal and rheological state of the Northern Argentinian foreland basins". It will be listed somewhere in the middle (see #300).

**Comment by cmeessen** [comment]
Darn, many apologies @dmijatovic I did not pay attention and accidentially moved the license in the wrong branch. Would you like to force push to remove the commit?

**Comment by dmijatovic** [comment]
> Darn, many apologies @dmijatovic I did not pay attention and accidentially moved the license in the wrong branch. Would you like to force push to remove the commit?

@cmeessen No probs ;-). I just wanted to push your text suggestions and noticed the conflict. I will force push in a minute to remove your license commit.

**Comment by ewan-escience** [comment]
>     2. Imported mentions cannot be edited and thus not be featured, which is a pity.
This is on purpose. We are writing a scraper that will scrape data from Crossref and DataCite and update the database entries, so any manual changes will be overwritten anyway. If data is wrong, it should be corrected at the source. And we plan to make the featured flag a property of the relation between a mention and the software/project instead of a property of the mention itself, so you will be able to edit the feature status later.

**Comment by cmeessen** [comment]
> This is on purpose. We are writing a scraper that will scrape data from Crossref and DataCite and update the database entries, so any manual changes will be overwritten anyway. If data is wrong, it should be corrected at the source. And we plan to make the featured flag a property of the relation between a mention and the software/project instead of a property of the mention itself, so you will be able to edit the feature status later.

Understandable. If this is already planned I would not open a new issue for that - unless you would like to?

**Review by ewan-escience — APPROVED** [review]

**Pull request merged**
