### PR TITLE
Auto fill in from doi - suggested extension

### LINKED ISSUE #201: Pull authors from zenodo
Message from Peter 

Hi, I was adding my software to the RSD, but wondered whether filling some of the information could not have been done automatically. After having it filled in for the citation.cff and on Zenodo, I needed to fill in things like the contributors again in the RSD. Would be nice if this could be somehow synchronized maybe?

### PR DESCRIPTION
**Pull request by dmijatovic**
# This is extension of #248

Closes #248 
Closes #201

Changes proposed in this pull request:
* Rename autofill... component to GetContributorsFromDoi
* Add deduplication of already present contributors using family_names

How to test:
* `docker-compose down --volumes`: to remove old db
* `docker-compose build`: to build
* `docker-compose up`: to start
* data-migration is optional
* login using test idp, eg professor1
* create new software
* add valid DOI
* navigate to contributors and use import contributors button, try multiple times

image

## Update on incorrect name in the image
The DOI I used is hosted by crossref. When using crossref api the name seem to be correct. I am not sure if we can do anything to improve response from datacite.org. For now we can ignore this error because all of DOI we use are hosted by datacite.

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by dmijatovic** [comment]
@ruester and @cmeessen Can you let us know if you have any remarks on this changes made to original PR #248

**Review by ruester — APPROVED** [review]
Maybe we can unify the margins for the different section at the subpage "Contributors". Currently there is more space under "Import contributors" than above.

**Comment by ruester** [comment]
Many thanks, looks good! How do we proceed with the two PRs?

**Comment by ruester** [comment]
Great! I have nothing to add for now, we can merge if you want :wink:

**Review by ewan-escience — APPROVED** [review]
Nice work! We have to think how to improve de-duplication in the future. There could be two different people with the same full names both without an ORCID en email address.

**Pull request merged**
