### PR TITLE
Codemeta server

### LINKED ISSUE #1128: CodeMeta server
Make a service that can export software pages to the [CodeMeta format](https://codemeta.github.io/terms/).

### PR DESCRIPTION
**Pull request by ewan-escience**
## CodeMeta server

Changes proposed in this pull request:

* Add CodeMeta server that can serve for each public software page the CodeMeta data

How to test:

* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale data-generation=1`
* Browse http://localhost/software to collect some slugs
* Visit http://localhost/codemeta/some-slug and check that the CodeMeta data corresponds to the software page
* Check for missing data that is crucial for this first version
* Check the README.txt
* The actions can only be tested when merged into main 🙁, but read the files to see if they seem reasonable

Closes #1128

PR Checklist:

* [ ] Increase version numbers in `docker-compose.yml`
* [x] Link to a GitHub issue
* [x] Update documentation
* [ ] Tests

### CODE REVIEW

**Review by dmijatovic — APPROVED** [review]
Nice work. I think this is good starting point.

I have few suggestion I expect to be beneficial as the service grows:
- Log message that server is running at port x at the start of the service
- Listen to interrupt and log "gracefully closing the service".
- Add api version into the route (/codemeta/api/v1)
- Move route handlers code into a separate file(s)
- Add basic tests for each route?

**Comment by cmeessen** [comment]
Works as described :+1: Will codemeta be the only metadata format that the RSD will offer in the future? If not, would it make sense to use a more generic route route, e.g. `/api/metadata` and use arguments to specify the desired metadata format? This could make it easier and more stable to use in case there will be support for other formats in the future.

**Comment by ewan-escience** [comment]
> Works as described 👍 Will codemeta be the only metadata format that the RSD will offer in the future? If not, would it make sense to use a more generic route route, e.g. `/api/metadata` and use arguments to specify the desired metadata format? This could make it easier and more stable to use in case there will be support for other formats in the future.

Nothing concrete planned, but who knows. I don't think this is part of the API, so how about `/metadata/codemeta` or `/metadata/codemeta/v3`, since we use V3 of the spec?

**Comment by ewan-escience** [comment]
I changed the path to `metadata/codemeta/v3`.

**Pull request merged**
