### PR TITLE
247 project and software maintainers

### LINKED ISSUE #247: Edit project - Maintainers
On edit project page the creator of the project should be able to add new maintainers to the project.

The page should have two sections:
- maintainers list, for showing existing maintainers
- adding maintainers by search or by creating invitation link

## Search for maintainers
The search should be similar to other async autocomplete

## Invite new maintainers
At the first stage, this option should create a link with the unique key that can be e-mailed to someone. This person then should login to RSD using supported login providers,

Related to #196 

## Database

Create table to hold project maintainer invites. Maybe set unique index on project + created_by + claimed_by?

```sql
-- create table for maintainer's "magic link" invitations
CREATE TABLE invite_maintainer_for_project (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	project UUID references project (id),
	created_by UUID references account(id),
	claimed_by UUID references account(id),
	claimed_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
```

## Auth endpoint (backend)

- create protected auth endpoint to claim a maintainer role for an project. The request will be passed from the frontend after user is logged in to RSD
   - endpoint: /auth/invite/project/{invite-uuid}
   - method: POST
   - headers: Authorizaton: Bearer {{token}}
   - body: json
```json
{
  "invite_id": "2dddb5bd-8329-4b76-a450-2fa57a2d56c1",
  "claimed_by":"d2c07306-06cf-4625-a9cf-99b3515a2a44" 
}
```
  - expected response: 200, 400, 500
  - expected body on 200:
  ```json
{
  "title": "This is project title",
  "slug": "project-slug-to-create-link-to-project"
}
   ```

# First draft

image

### LINKED ISSUE #258: Edit software - maintainers
Create maintainers section on edit software page. The approach should be similar to one we are now developing for the maintainers of the project page

### PR DESCRIPTION
**Pull request by ewan-escience**
# Initial maintainer invitation flow for projects and software

Changes proposed in this pull request:

* Add an invitation table in the database for projects
* Add a function to the database to accept an invitation to become a maintainer for a project
* Add a function to the database that allows you to see information of the other maintainers of a project that you maintain
* The frontend facilitates using these features by allowing to generate invitation urls, by giving an overview of maintainers and by allowing to delete maitnainers

How to test:

* Rebuild the project
	* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale scrapers=0`
* Login and create a project
* On the admin page, go to maintainers
* Generate an invite url
* Log in as a different user and go to the invite url you generated above
* You should now be a maintainer of that project
* Try to delete a maintainer, when one or on the last maintainer delete icon is disabled

Closes #247
Closes #258

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by dmijatovic — APPROVED** [review]
Nice teamwork! It works as intended and imho is a solid starting point upon we can extend this section based on received feedback.

**Review by jmaassen — APPROVED** [review]
Works as expected. One potential issue I noticed is that you are allowed to remove the final maintainer in the project leaving it orphaned?

**Review by cmeessen — CHANGES_REQUESTED** [review]
Nice one, this is working well for me :+1:

A thing I stumbled across was when I wanted to copy the invite link, the context menu said "Copy email address". I like the idea to have a  pre-generated mail with the link, but this was a bit confusing, since I was looking at an HTTP link. My suggestion would be to have a message with this link that says "Click here to send a mail with the invite link", and then in the next line display the link itself (but without the `a` tag). Next to the link could be a button that will copy the link to the clipboard.

**Review by cmeessen — APPROVED** [review]
Awesome :)

**Pull request merged**
