### PR TITLE
Add table repr for highlighted categories

### LINKED ISSUE #1217: upgrade tailwindcss package
I'm currently working on the table representation of category hierarchies (#992) and I'm facing an incorrect rendering when using tailwinds [subgrid](https://tailwindcss.com/docs/grid-template-columns#subgrid): Cells inside the subgrid are rendered vertically instead of horizontally. I tried tailwindcss v3.4.3 and it is fixed there.

### PR DESCRIPTION
**Pull request by fembau**
* add table representation for highlighted categories (was separated from #1143 )

Closes #1217

### CODE REVIEW

**Review by ewan-escience — CHANGES_REQUESTED** [review]
See the comment from @cmeessen.

**Comment by dmijatovic** [comment]
Yes, definitely something unexpected happening. Further investigation is needed. I'll have a look if I can find the culprit.

**Review by cmeessen — CHANGES_REQUESTED** [review]
For mobile devices, please display the bullet list instead of the table.

**Comment by fembau** [comment]
fixed table rendering and added different representation for small screens

**Review by ewan-escience — APPROVED** [review]

**Review by cmeessen — APPROVED** [review]
Works as expected, great work :+1:

**Comment by fembau** [comment]
@ewan-escience You replace the basic data structure of category tree by the new class `TreeNode`. I see a lots of
```
const category = item.getValue()
if (category === null) {
    return null
}
```
Why `value` of a tree node is allowed to be `null`. Makes no sense for me :thinking:

**Comment by ewan-escience** [comment]
> Why `value` of a tree node is allowed to be `null`. Makes no sense for me 🤔

Because during initalisation of the tree, I need the value be null sometimes, see e.g . the function `categoryEntriesToRoots` in `frontend/components/category/apiCategories.ts`.

**Comment by ewan-escience** [comment]
I can maybe do without `null` by keeping track of the children of a not-yet-existing node using an extra hashmap. Not having `null` for the value would indeed be a lot more convenient.

**Pull request merged**
