### PR TITLE
feat: edit contributor and team member modal options

### LINKED ISSUE #450: Use controlled vocabulary for software contributor roles
We have received a [suggestion](https://github.com/hifis-net/RSD-as-a-service/issues/24) that it would be useful to use a controlled vocabulary for the contributor roles. The following options were mentioned:

* [DataCite Contributor Role](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#7a-contributortype)
* [ISO19115 CI_RoleCode](https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml)

### LINKED ISSUE #1152: Easier reuse of person pictures
When adding a new contributor or team member, you can reuse a picture if we found a matching name in the RSD. However, when editing a person, you cannot do this and have to upload a new picture. It should be possible to also reuse a picture when editing a person, also from the admin view "RSD contributors".

### PR DESCRIPTION
**Pull request by dmijatovic**
# Edit contributor and team member

Closes #450
Closes #1152 

Changes proposed in this pull request:
* edit contributor avatar, roles and affiliation using aggregated values from other RSD entries. 
* edit team member avatar, roles and affiliation using aggregated values from other RSD entries.
* Avatar and affiliation values are aggregated based on contributor/team member ORCID.
* use of "person" shared components for "edit" modal and search/find option
* moved methods to "hook" files
* FIX: removed **fuzzy** search "indicator" from ORCID search url (because it does not produce expected behaviour).
* FIX: **improve deduplication at import of contributors**, use last_name+first name instead of only last_name.
* rsd admin can update rsd contributor avatars. The avatars are aggregated on "display_name" (first name + last name) or ORCID.

How to test:
* `make start` to build and generate test data
* login as rsd admin
* navigate to edit software page, contributors section.
* test all options: create, find, edit and delete contributor. You should be able to select avatar images, roles and affiliation based on the data already present in RSD
* test contributors with ORCID and without ORCID
* navigate to edit project, team members section
* test all options: create, find, edit and delete contributor. You should be able to select avatar images, roles and affiliation based on the data already present in RSD
* test team members with ORCID and without ORCID
* test rsd admin edit avatars section:
   *  first add yourself to number of software and project items and upload different images
   * then navigate to rsd admin, rsd contributors page
   * search for yourself by first or last name. You should see a list of your entries. In the avatar column you will see avatar and the count of options. If there is a more than 1 avatar option you will be able to click on avatar and change it.

## Contributor modal (example)
image

## Team member modal (example)
image

## Rsd admin - contributors
image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests
*

### CODE REVIEW

**Comment by jmaassen** [comment]
I seem to have found an unrelated bug? 

When adding a team member to a project, I get the following options: 

Screenshot_2024-09-13_09-24-19

However, when I keep typing, this happens: 

Screenshot_2024-09-13_09-24-34

I would expect the "Boyd Edwards" from ORCID to remain at the top, since "Boyd E" is an even better match than just "Boyd"?

**Comment by jmaassen** [comment]
Another comment (not sure if this is expected behavior): 

When testing, I added my own name + orcid as a contributor and team member, and added several mugshots. Some of them randomly seemed to disappear when switching between different projects/software. 

It took me a while to figure out that this is because the unused foto's are removed as soon as you switch to a different context. This may also confuse our users?

**Comment by dmijatovic** [comment]
@jmaassen & @ewan-escience I made changes requested by Jason. Can you validate again. Thanks!

**Comment by dmijatovic** [comment]
@jmaassen en @ewan-escience I added avatar update for rsd admin. Can you test all features again please?

**Review by ewan-escience — APPROVED** [review]

**Comment by jmaassen** [comment]
I think there is still a small bug in de admin part? 

- I have a contributor A with orcid and multiple avatars. 
- I copy that orcid to contributor B with a different name and without orcid or avatar.
- The avatar list in the admin interface for contributor B does not update. It remains empty also after a reload.
- If I go to the software pages mentioning contributor B and click on edit contributor, it does show me all the avatars.

**Comment by dmijatovic** [comment]
@jmaassen Thanks for the remark. I extended aggregation in the rsd admin section to include ORCID too. 
Let me know if this approach is OK.

**Pull request merged**
