### PR TITLE
Add option to disable cropping of project images

### LINKED ISSUE #443: image resolution for project pages
For the project pages, uploaded images are expected to be of a certain dimensions (resolution). I think it is something like 1024x576. If this is not the case, the image is simply cutoff after the upload. Could you provide this information (on aspect ration and size of the image expected) in the image upload area. Currently the instruction is only on the expected size of the file:
Screenshot from 2022-07-26 09-55-03
.

### LINKED ISSUE #452: Project image not suitable for logos
The project images are displayed as background images of an element with the properties

```css
background-position: center top;
background-size: cover;
```

Whilst this is very good for displaying picutres, it makes project logos unreadable. Here is an example for the HIFIS logo:

image

image

A possible solution would be to allow the user to influence the `background-position` and `background-size` properties.

### PR DESCRIPTION
**Pull request by ruester**
# Add option to disable cropping of project images

Fixes #452 
I think this also fixes #443 

Changes proposed in this pull request:

* add another switch to the project information page, so that the user can decide how the project image is displayed: cropped of (an zoomed in) or showing the whole image within the extend of the image container

image

How to test:

* ```
  docker-compose down --volumes # there are db changes
  # if you use the frontend dev mode
  docker-compose build database
  make dev
  # else
  docker-compose build --parallel
  docker-compose up
  ```
* create a new project and upload a wide image for it
* the image should be cut off by default
* setting the switch "Always show the whole image" does not crop the image and instead lets it show contained fully in the surrounding image container
* other components showing projects also use this new value to show the image cropped or contained

Still to do:

* this PR also includes a DB change, so we need a migration script... Since I have no experience with `migra`, I hope someone from NLeSC could create this migration script?

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [X] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by cmeessen — APPROVED** [review]
I like it, thank you :+1: Let's see what the others are thinking.

**Review by ewan-escience — APPROVED** [review]

**Review by dmijatovic — APPROVED** [review]
Excellent work! Please merge asap as we would like to include this feature in the next release (probably this Friday).

I pushed one minor adjustment for the image height on the project page that will improve image presentation with this new option.

**Comment by ruester** [comment]
Do you have a migration script for the DB? At which place should it be documented? Or can we skip the migration for this change?

**Comment by ewan-escience** [comment]
I was planning to add a migration script to https://github.com/research-software-directory/RSD-production/tree/main/database-migration/migration-scripts when we make a new release, hopefully on Friday.

**Comment by ruester** [comment]
Great, many thanks :+1:

**Comment by ewan-escience** [comment]
For future reference, the script is here: https://github.com/research-software-directory/RSD-production/blob/main/database-migration/migration-scripts/1.2.2-to-1.3.0.sql

**Pull request merged**
