### PR TITLE
923 add categories for software

### PR DESCRIPTION
**Pull request by dmijatovic**
PR #946 was polished and prepared for v2 -> created this new PR.

### How to test:
remove extra file extension from `999-add-categories.sql.example`, optional edit file and finally build application as usual.

On a software edit page you will find a new headline "Categories".

### CODE REVIEW

**Comment by fembau** [comment]
@dmijatovic it seems that only you can switch off draft state ;) Please also review this PR (can not add you)

**Comment by dmijatovic** [comment]
@fembau Shell we close the other PR in favour of thisone then?

**Review by ewan-escience — CHANGES_REQUESTED** [review]
Nice work! I have a few small comments/questions:

- What is `frontend/.yarn/releases/yarn-1.22.19.cjs`? It is 5MB in size. Can it be removed? Same for `frontend/.yarnrc.yml`.
- Please remove the `AND is_published` from the policy 'anyone_can_read' on `category_for_software`, that logic is already covered by the policy on software.
- Please capitalise 'as' everywhere in `category_paths_by_software_expanded`
- In the test, please put the `User` class in a dedicated file.
- I'm not sure about the `User` constructor using HTTP requests to initialise itself. I think it's better to have a static factory method somewhere that does this for you and returns a `User` upon success. But this could be done later as well.
- Line 273 can be deleted as it only contains a unnecessary semicolon.
- Maybe a test can be added that tries to create a cycle in the categories.
- Is it intentional that there is not an admin interface to add/edit categories?

**Comment by jmaassen** [comment]
Works well, some comments: 

- I was slightly confusing at first that the categories in the drop down list when selecting are different that what you see after selecting. This was mainly because in the example the "Category X aka X.Y.Z" is shorter than the short name ;-)

- having an icon is a nice touch. Do we have documentation on which icon names are valid? Currently it says "science".

- for consideration: can we use the same approach for projects? You could say that "Research domains" is simply the top level category.

**Comment by dmijatovic** [comment]
@fembau If you need the yarn settings @ewan is referring, please add these to .gitignore file. That way these will not be included in the repo.

**Comment by fembau** [comment]
Thank you for your feedback! :)

@ewan-escience @dmijatovic:
- ejected yarn topic from this PR. see also [discussions/843](https://github.com/research-software-directory/RSD-as-a-service/discussions/843)
- _Please remove the AND is_published from the policy 'anyone_can_read' on category_for_software, that logic is already covered by the policy on software._ --> This should prevent reading information related to not-published software.
- moved `User` to separate file + added factory. Also created a `class Commons`
- beautified code :)
- added test for cyclic categories.
- admin interface is postponed to #952

@jmaassen:
- improved text of example categories :)
- select leafs only: yes, as proposed in the related issue I think this is the proper way of using a catalog/vocabulary here... Anyhow it is currently not prevented by the backend...
- icons: until we have #975 available icons are defined in [frontend/components/typography/Icon.tsx](https://github.com/research-software-directory/RSD-as-a-service/pull/984/files#diff-8fee6e327b2bad51af55a1fa895c339f5c848709253edf586cc0ba0286878013). I put a note into the examples file.
- also for projects: yes, this is intended. Kept this out of this PR to make it smaller and setup a generic foundation first ;)

We have already seen that generic categories inspire lots of ideas what we could do next :)

**Comment by ewan-escience** [comment]
> This should prevent reading information related to not-published software.

But that is already covered by `SELECT 1 FROM software WHERE id = software_id`, which takes the published status into account because of the row level security on software.

A small pet peeve of mine, the example SQL file is indented with spaces instead of tabs. :)

That's all from me, nice work!

**Review by cmeessen — APPROVED** [review]
Awesome, this is looking really good already.

I created #992 to address one aspect that was part of #741 but was not implemented yet.

**Review by ctwhome — APPROVED** [review]

**Review by ewan-escience — APPROVED** [review]

**Pull request merged**
