### PR TITLE
Add more info to software licenses

### LINKED ISSUE #1033: Add open source flag to edit software
# Open source flag for software

There is a need to have binary indication for user to indicate if the software is open source or proprietary (closed source). After discussing the feature with our partners we decided to start with basic implementation:

- Add open source / proprietary (single) choice on Add software page. Open source is default choice (image 1)
- Add same choice on Edit software page in the license section. (image 2)
   - Open source / proprietary choice
   - Find or add new license value in both cases
- Expected future adjustments:
   - For each license we can have license label and the link to a license page text. For open source licenses this info is available in spdx.json. The Concept DOI has link to license page in some cases (not always). When adding new license the user should provide url to license page.
   - We would like to refactor the content. "Software information" page could be split into "Basic info" and "Software metadata". We would like to place Concept DOI, Keywords, Licensing and maybe Contributors into "metadata" page.

## Add software 

image

## Edit software license info
image

### PR DESCRIPTION
**Pull request by dmijatovic**
# Software licenses

Closes #1033 
Closes #1041

Changes proposed in this pull request:
* Save more information about software license (name, reference and open_source flag)
* Refactor: move configuration of links & metadata section to separate config file 
* Chore: fix found type errors
* Fix failing tests 
* Use short identifier as main label and show the long license name on mouseover. We also provide the link to the license page (by default spdx page).
* Search for license by short identifier or by long name
* For custom licenses providing reference link (url to license page) is required

How to test:
* `make start` to build and create test data
* Login and create new software
* Go to links & metadata section and add licenses:
  * Type Apache and select license
  * Try import using concept DOI 10.5281/zenodo.6379973
  * Type unknown license name like `My new fancy license` and add custom license
* Preview software page, confirm the licenses are shown and the links are working

## TODO!
** Create migration script to update all historical data for the spdx license entries **

## Edit software license page
image

## Add custom license
image

## Software licenses on software page
image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by cmeessen — APPROVED** [review]
Works as described :+1:

**Review by ewan-escience — CHANGES_REQUESTED** [review]
Doesn't work with existing data: empty license buttons on maintainer view, import hangs forever, can't add new licenses.

**Comment by jmaassen** [comment]
Some comments: 

- the search in the license currently only searches the full name, not the abbreviation. This makes widely used licenses like GPL or LGPL hard to find, as you need to know the full name
- for the keywords, we have a "select from top-X or start typing option". This may also be useful for licenses? There are probably ten or so licenses that almost everyone uses.
- for the question if a custom license is open source the word "type" is not needed. Could also rephrase as "This is an open source license"

Screenshot 2024-04-15 at 09-18-56 Edit software Research Software Directory

**Comment by dmijatovic** [comment]
@jmaassen I have improved search functionality and we pre-load short list of licenses. In addition, I reverted back to using license id's and show long name on mouse over.
Can you check this version, please?

**Comment by jmaassen** [comment]
When searching, sometimes results are shown that are initially confusing. For example, when searching for "mpl" one of the results is "BSD-2-Clause": 

Screenshot_2024-04-16_15-59-53

as it turns out, this is caused by the word "Simplified" in the full description ;-)

Would it be an option to not show the full name in the mouse over, but instead add it in the list? Something like: 

- **BSD-2-Clause** (BSD 2-Clause "Simplified" License)
- **GPL-3.0-only** (GNU General Public License v3.0 only)
- **Apache-2.0** (Apache License 2.0) 

Also, given the long list of licenses, there is a high probability of a match when trying to add your own license, so it may be good to always show the "Add ..." option? 

Finally, when typing a license name like "adw", no options are shown, but there is also no indication that the shortest name you can add is 4

**Comment by jmaassen** [comment]
Works great. We could consider removing the "deprecated" licenses, but I would have to check the exact meaning of those first.

**Review by ewan-escience — APPROVED** [review]

**Pull request merged**
