### PR TITLE
619: additional explanation login options

### LINKED ISSUE #619: Login popup: mention the ORCID whitelist

### PR DESCRIPTION
**Pull request by dmijatovic**
# Additional info per login provider

Closes #619 

Changes proposed in this pull request:
*  Additional property is added to provider object in order to show additional information about the provider and who can make use of this provider. To accommodate additional text the layout of the button is changed. Additional info text is added into service provider api (not in env file). 
* The quote is moved at the bottom of the modal
* In SURFconext text link to IdP listing of RSD service is added
* In ORCID text mailto link is added to contact rsd team
* At the bottom of the login modal a link to sign in page of RSD documentation is added. The link is added into settings as `host.login_info_url`

How to test:
* Ensure you have proper env definitions for login providers (contact me for values of env file)
* Ensure you enabled the providers in .env file variable (it specifies the list order too)
`RSD_AUTH_PROVIDERS=SURFCONEXT;ORCID;HELMHOLTZAAI;LOCAL`
* `make start` to restart all (when you done use docker-compose down)
* click on login button and you should see a list where SURFconext and ORCID have additional info as in the example below
* Pay attention to SURFconext and ORCID info text and links. I am in doubt about the links because these are in the button. So main click on the button will forward you to provider while click on text link should open new page. 
* All improvement ideas are welcome! Pay attention to provided texts in particular.
* Note! If you are changing .env values you need to restart docker-compose to reload .env values (`docker-compose down && docker-compose up` - probably there are other ways to achieve same result ;-)

## Desktop/tablet layout
image

## Mobile layout
image

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by cmeessen** [comment]
I added a small description for the AAI:

image

Something I stumbled across: as a user I would not understand what the \* means behind the login options. An explanation would be very helpful.

**Comment by dmijatovic** [comment]
> I added a small description for the AAI:
> 
> image
> 
> Something I stumbled across: as a user I would not understand what the * means behind the login options. An explanation would be very helpful.

Good point. The ideas was to put * before the info text, but because the text it is already under the title, it seem me that * can be actually removed.

**Comment by jmaassen** [comment]
It would be good to tweak the text a bit to make it more consistent. Currently, is uses a mix of "Sign in" and "Signing in". Best to use "Sign in" everywhere?

There is a "the" missing in the SURFconext description: "enabled RSD service" -> "enabled the RSD service"

For ORCID: "invited by RSD administrators" -> "invited by the RSD administrators" (although this one can also do without)

Maybe we could change the Carl Sagan quote with some text: "For more information about signing in to the RSD click here", where "here" links to "https://research-software-directory.github.io/documentation/signing-in.html" ?

**Comment by dmijatovic** [comment]
Thanks for the feedback! The update are performed and I will merge this PR soon

**Pull request merged**
