### PR TITLE
Support for custom themes via volume mounts and settings.json

### PR DESCRIPTION
**Pull request by dmijatovic**
# Add support for loading different themes at runtime

**This is WIP, created to explore the possibility of applying Helmholtz styles and typography**. 

Next steps are:
- Helmholtz to examine the approach and try to apply all their styles using the code in this PR
- RSD team to provide support and explain how the solution works

## Changes proposed in this pull request
* The theme approach is adapted to load different, predefined, themes at the runtime using volume mounts of frontend image.
* The homepage is loaded based on the host value provided in the mounted settings.json file. If host is not provided in the settings.json the default rsd homepage is loaded.
* If `settings.json` is not provided via volume mount the default settings file is loaded (public/data/settings.json)
* if `index.css` file with font imports is not provided via volume mount the default index.css file is used (public/styles/index.css)
* When using default RSD settings one does not need to provide volume mounts in the frontend service

## Open issues
* `Helmholtz footer`: different footer with additional image, different contact email and custom links to be added. My preference is to extend settings.json with these additional properties

```json
{
  ...other props
   "footer":{
      "links":[{"label":"Link label", "url":"https://some-url.com"}],
      "logo_svg":"<svg></svg>",
      "contact": "some.email@contact.com",
   }
}
```

* `Dark/light theme switch`: the basic infrastructure is created but the complete implementation involves additional steps
   * integrating theme switch in tailwind portion
   * integrating theme switch in tailwind markdown plugin. It uses it's own css variables
   * integrating theme switch in material-ui themes. Investigate use of css variables

How to test:
* `docker-compose build` to build the solution
* create `hmz` folder in the deployment directory. Note I have added hmz folder in the .gitignore file
* Copy all folder and files from the rsd folder into hmz folder. Provide your values in the index.css, settings.json files and upload your custom images used on your homepage. * 
* change values in docker-compose frontend service to:

```yaml
  # frontend definitions example to mount custom theme
  # add volumes as in this example to load index.css and settings.json
  frontend:
    ...other definitions
    volumes:
      # mount local styles folder into styles folder of frontend app (index.css file is the access point)
      - ./deployment/hmz/styles:/app/public/styles
      # mount custom settings (theme colors and typography definitions) into data folder of frontend app
      - ./deployment/hmz/data:/app/public/data
      # mount custom images used on custom home page (for helmholtz only)
      - ./deployment/hmz/images:/app/public/images
    ...other definitions
```
* `docker-compose up` to start. Confirm the helmholtz blue theme and homepage are loaded properly
image
image
* stop docker and unmount the images using `docker-compose down`
* change volume mounts to rsd 
```yaml
  # frontend definitions example to mount custom theme
  # add volumes as in this example to load index.css and settings.json
  frontend:
    ...other definitions
    volumes:
      # mount local styles folder into styles folder of frontend app (index.css file is the access point)
      - ./deployment/rsd/styles:/app/public/styles
      # mount custom settings (theme colors and typography definitions) into data folder of frontend app
      - ./deployment/rsd/data:/app/public/data
      # mount custom images used on custom home page (for helmholtz only)
      - ./deployment/rsd/images:/app/public/images
    ...other definitions
```
* start again with `docker-compose up`
* confirm that default RSD home page and the styles are loaded properly
image
* stop service and unmount with `docker-compose down`
* remove or comment out the volume definitions in the frontend service
* `docker-compose up` to start
* confirm that default RSD layout is loaded (even without volume mounts)

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by dmijatovic** [comment]
@cmeessen Thanks for the feedback. I will return to this PR after I implemented #393. That PR will enable custom pages written in markdown. If markdown custom page is sufficient for your homepage we might think how to enable it for home page too.

I also want to try approach with local font hosting. I believe that would be preferred approach for Helmholtz fonts. I'll let you know when I resume work on this PR

**Comment by dmijatovic** [comment]
@cmeessen Can you take a look at this version? I rebased so you will need to pull branch from scratch again. I fixed the color of the buttons and I added routing for different home pages. I took your index code and adjusted a bit to work in this new setup. I just noticed that I am missing some images which are not in our repo. This is the first version without custom Helmholtz fonts.

**Comment by dmijatovic** [comment]
@cmeessen I have completed the initial setup as I would like to implement it. Can you have a look? I notices we are missing some images and decided to enable mounting of image folder too.

**Comment by cmeessen** [comment]
> @cmeessen I have completed the initial setup as I would like to implement it. Can you have a look? I notices we are missing some images and decided to enable mounting of image folder too.

Thank you, it works as described. It doesn't work using `yarn dev` though, which is unfortunate for development as we would have to build the frontend on every change during development. Is there a way to make this work?

**Comment by dmijatovic** [comment]
@cmeessen Is there a way to make this work in dev? When working in dev you can change the files directly in frontend/public folder and reload the page in order reload settings.json.

**Comment by cmeessen** [comment]
@dmijatovic: @ruester will take this one over and will finish it, so we can integrate it in our repo as well. Is there still something to do from your side?

**Comment by dmijatovic** [comment]
@cmeessen, @ruester Excellent! I would like to rebase this branch and resolve all conflicts after we create new release in order to have all new features included and validated. After that, if you need my support during the implementation do not hesitate to contact me.

**Comment by dmijatovic** [comment]
@cmeessen, @ruester I have upgraded features from this PR to the latest version and moved to a new PR #506.

**Comment by ruester** [comment]
Many thanks, I will test this new PR with our customizations :+1:

**Pull request closed without merging**
