### PR TITLE
RSD v2 release

### LINKED ISSUE #655: Behavior of filter for projects
For projects, I can now filter on both keywords and research domains (yay!). However, when selecting one of the filters, the other does not update the list of projects.

For example, selecting "Big Data (12)" as a keyword filters the project cards to the 12 that match, but the "Research Domain" filter still shows the full list. This is not really intuitive, as there is a high chance of me picking a research domain which has 0 big data projects. 

It would be better if the lists are linked somehow? Updating one reduces the list of the other to those that match?

### LINKED ISSUE #789: Match filters counts with selected options
related to #655 
The current filter panel shows the number of keywords, program languages, and licenses that exist for all the software. 
Is nice to have, but also gives a better indication of what types of results are available base on a filter selection.

It is probably needed to create an RPC that returns the filtered counts the based on:
- search input
- Keywords (including the keywords list counts itself)
- Programm languages (idem)
- Licenses (item)

Example: 
- After selecting the keyword "GPU", the rest of the counters should be updated with taking in account the new filter
image

### LINKED ISSUE #792: New design for organization page
Follow the new UI to adapt it to the organization page.

New organization page design! the main changes go to the organization information and the display of the tabs: now horizontal. The settings tab also gets a redesign to group together what an organizer maintainer can access, to edit everything in one place.

- [ ] About page (See design below)
- [ ] Software and project page: same design like the stand-alone software and project pages
- [ ] Research Units: same design than an organization, but filtered by research unit
- [ ] Settings: new design. keep the previous vertical tabs inside the settings page (see wireframe below)

### Organization information with About page open
image

### New settings tab
The design is only wireframed. It's content 
image

#### ROR SVG icon
```svg
<svg width="20" height="22" viewBox="0 0 20 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M4 7L7.4641 1.75H0.535898L4 7Z" fill="#222425"/>
<path d="M4 15L7.4641 20.25H0.535898L4 15Z" fill="#222425"/>
<path d="M16 7L19.4641 1.75H12.5359L16 7Z" fill="#222425"/>
<path d="M16 15L19.4641 20.25H12.5359L16 15Z" fill="#222425"/>
</svg>

```

#### Type icon
```svg
<svg width="16" height="15" viewBox="0 0 16 15" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0H3.54286V1.65536H1.90857V13.3339H3.54286V15H0V0ZM16 15H12.4571V13.3446H14.0914V1.66607H12.4571V0H16V15Z" fill="#222425"/>
</svg>

```

### LINKED ISSUE #803: Adapt new design to organizations grid
apply new cards design to organizations

depends on: https://github.com/research-software-directory/RSD-as-a-service/issues/806

image

### LINKED ISSUE #806: Scrape organization location
In order to place the organizations on a map (see image), we need a scraper that pulls the location of an organization based on its ROR.

We are aware that ROR only has the coordinates for the city where the organization is based. Which could it be sufficient for now?

Documentation: https://maplibre.org/maplibre-gl-js-docs/example/geojson-markers/

To facilitate the front end, the column "location" inside the table "organisation" could have JSON format:

```js
location: {
  country: "The Netherlands",
  place: "Amsterdam",
  lat: 32.234234234
  long: 4.1223413234
}
```

image

### Request
```html
https://api.ror.org/organizations?query=https://ror.org/01ppy6j62
```
### Response
```json
{
	"number_of_results": 1,
	"time_taken": 1,
	"items": [{
		"id": "https://ror.org/01ppy6j62",
		"name": "Geophysics GPR International",
		"email_address": null,
		"ip_addresses": [],
		"established": 1974,
		"types": ["Other"],
		"relationships": [],
		"addresses": [{
			"lat": 45.53121,
			"lng": -73.51806,
			"state": null,
			"state_code": null,
			"city": "Longueuil",
			"geonames_city": {
				"id": 6059891,
				"city": "Longueuil",
				"geonames_admin1": {
					"name": "Quebec",
					"id": 6115047,
					"ascii_name": "Quebec",
					"code": "CA.10"
				},
				"geonames_admin2": {
					"name": "Montérégie",
					"id": 6076966,
					"ascii_name": "Montérégie",
					"code": "CA.10.16"
				},
				"license": {
					"attribution": "Data from geonames.org under a CC-BY 3.0 license",
					"license": "http://creativecommons.org/licenses/by/3.0/"
				},
				"nuts_level1": {
					"name": null,
					"code": null
				},
				"nuts_level2": {
					"name": null,
					"code": null
				},
				"nuts_level3": {
					"name": null,
					"code": null
				}
			},
			"postcode": null,
			"primary": false,
			"line": null,
			"country_geonames_id": 6251999
		}],
		"links": ["https://geophysicsgpr.com/"],
		"aliases": [],
		"acronyms": [],
		"status": "active",
		"wikipedia_url": "",
		"labels": [{
			"label": "Geophysique GPR International",
			"iso639": "fr"
		}],
		"country": {
			"country_name": "Canada",
			"country_code": "CA"
		},
		"external_ids": {
			"ISNI": {
				"preferred": null,
				"all": ["0000 0004 0471 1571"]
			},
			"GRID": {
				"preferred": "grid.450825.e",
				"all": "grid.450825.e"
			}
		}
	}],
	"meta": {
		"types": [{
			"id": "other",
			"title": "Other",
			"count": 1
		}],
		"countries": [{
			"id": "ca",
			"title": "Canada",
			"count": 1
		}],
		"statuses": [{
			"id": "active",
			"title": "active",
			"count": 1
		}]
	}
}
```

### LINKED ISSUE #823: Ensure use of theme colors in tailwind classes
The default tailwind config file offers more color options than we have defined in our theme. In out html markup there are few places where these non-theme colors are used (home page is one example). 

Using non-theme colors might create undesired theme issue for users of zelf-hosted RSD instances which want to apply their custom colors. 

The color options are shown by tailwind VS code plugin. We  can limit color options by moving `colors` object from `extend` section directly into `theme` section. The approach should reduce use of non-theme colors in tailwind css by their class names. 

In addition to tailwind configuration change we need to ensure (find) all non-theme colors used are added to our theme colors or replaced with an alternative color from our theme. The theme colors are defined in frontend/public/data/settings.json.

### LINKED ISSUE #824: Define core design tokens for v2 (discussion)
We would like to change design in RSD in version 2. RSD v1 frontend counts >1100 files (lot of these are UI components).
In order to have v2 components in the same design "logic" it is necessary to define basic design tokens to be used in all components. This will ensure consistency throughout the application and increase reusability of components.

- **Buttons**: 
     - primary button  (default)
image
    - primary, secondary buttons in modals (see Modals section)
  
- **Info/Alert boxes**: box with icon, with or without title. Text and url links only.
image
image
image

- **Search box / Autocomplete input**: current  search box component 
image

- **Inputs** (text/number/date): current input version, title - open input - help text/error message underneath
image

- **Modals**: current modal approach, header with bottom border, navigation with top border. Full screen on "small screens" < 640px
image

- **Rounded borders**: currently no rounded borders are used on buttons, panels etc. (or a minimal rounded border with size of 2px)

Related to design changes for #820 (see image)

image

### LINKED ISSUE #838: Add the possibility to display the software cards by Grid or List mode
Show the software list on a list: 

Design
- [ ] Visual Design

Implementation
- [ ] List implementation
- [ ] Store the decision on localStorage

for example: 
image

image

### LINKED ISSUE #888: Project overview page v2
Upgrade project overview page to similar layout as new software overview page.

There should be two layout options: grid and list (see example)
Order and filter panel on the left side (see example)

Order (descending): Impact, Output, Start date and End date
Filters: keywords, research domains, organisation

- Icons for counts on impact and output items. (Include tooltip -> Also for software card)

## Project Card Design
image

## Example software page (grid)
image

## Example software page (list)
image

### LINKED ISSUE #896: Adjust background color for the new UI
The design's gray background color is meant to be slightly different that white. But the current color in production differs. It is a darker gray which gives more protagonism to the background. 
I would like to keep the original design and set the background color to this value: #F5F5F7
image
image

### LINKED ISSUE #913: Improvement suggestions for organization card
In testing #912 (fixing #807) I came across some things we can improve in the organization cards:

- At the moment we don't provide an indication of the type of organization (research, education, commercial, etc.) Maybe this could be added somehow? 
- The short description of an organization is currently only on the card, but not on the organization page yet. This will be fixed in #792 I think
- The images used as logo in the test set are not that representative for real logos. We discussed this an decided to use some free to use real logos for testing instead. I will come up with a small set. 
- The bottom of the card is currently "unbalanced", as the software and project counters are on the left. This leaves a lot of white space on the bottom right. We could use this for additional information icons (as software and projects also have). Maybe showing some aggregated metrics is a good idea? For example "total number of releases" of all software of this organization, total number of mentions, total contributors with this affiliation, etc.

### LINKED ISSUE #916: Position correctly the highlights card on window resize
The current carousel only uses CSS for the complete iteration. However, it is impossible to calculate the distance between the first highlighted card with the left side of the content, which is centered and responsive, only with css.

In this task, i will add the necessary react code to calculate the distance and apply it to the scroll position of the carrousel.

See working example here: https://www.apple.com/store

image

### LINKED ISSUE #922: Non-existing organisation page shows 500 instead of 404
When visiting a non-existing organisation page, a 500 status message is displayed instead of a 404 status message. For software and projects, it is correct though.

### LINKED ISSUE #924: Pinning software seems confused
For I demo I wanted to change the set of pinned software for the eScience Center organization. I noticed a couple of bugs:

- When trying to pin Amber, the UI tells me it is pinned, but as soon as I go back to the organization overview it is unpinned again.
- I see a different set of pinned software for eScience depending if I am logged in or not. 

Normal view:

Screenshot 2023-06-27 at 15-01-10 Netherlands eScience Center Research Software Directory

Logged in view:

Screenshot 2023-06-27 at 14-57-36 Netherlands eScience Center Research Software Directory

Note that the pinning may be replaced with highlights? So I'm not sure if this is worth investigating

### LINKED ISSUE #932: Missing "Software Highlights" title to the section in Sofware Page v2
During a demo, we got a quick feedback comment about the new software highlights section in v2 to include the title of "Software Highlights" on top of the Cards to distinguish between them clearly. We had it originally in the design but we didn't put it on the final version.

image

image

### LINKED ISSUE #933: Small project status bar UI tweak
The current implementation shows a progress bar for each project as designed. After seeing the final result with the current data I think it looks rather cluttered. I have a proposal to keep the card a bit cleaner, while still keeping the message of the status: 
- Completed projects: show only starting and finish dates.
- In-progress projects: show dates and progress bar.
- Non-started projects: show dates and progress bar (gray bar)

As seen in the following example, the projects that are in progress are more prominent and they create a clearer distinction between completed and not started. As well as giving a less cluttered UI overall. 

image

### LINKED ISSUE #934: Add Status filter in projects page
There is currently no filter for Project status. Probably useful for PMs, it could help to have a filter based on Status with the following options (or similar):
- Pending
- In progress
- Finished

See the wireframe idea: 
image

### LINKED ISSUE #935: Software card counters not aligned correctly
The numbers for Counters and mentions don't align correctly to the right side of the card

image 

They should be together as sown in the following example: 
image

### LINKED ISSUE #936: Mentions counter displays null in the tooltip when the counter is 0 in Software page cards
Probably it would be an easier idea to not sow the counter in the tooltip, but just the label "Contributors" or "Mentions".
Otherwise, the label could be changed to "no contributions"

image

### LINKED ISSUE #937: Clear button is enabled when entering the Software and Project pages
When moving routes between Sofware and Projects pages for the first time, the filters bar has enabled the 'Clear' button but the number of filters shows 0.

I guess that the default sorting method should not enable the clear button.

image

### LINKED ISSUE #938: Alternative design for Verified organizations badge
The verified organization's current implementation is very strong. The colored ribbon attracts much attention, stealing protagonism from the logo and the name of the organization. Unless that is the desired effect, we can change the Verified badge into a more familiar and less prominent design, placing it at the bottom right of the card, similar to what we have with the contributors, and mentions icons on the Software cards.

### To illustrate this change, I came up with 3 different icon designs:

image

One of my favorite designs is number 1, which somehow has a cleaner shape, and it is also round as our RSD logo :)

### Other icons alternative could be: 
image

### Tooltip information or popovers
Following again the same example the in the Software card, the verified icon should have a tooltip indicating the label named. Or even a poppi hover with more information and a call to action, something like **Learn more**, or **Claim your organization**
image

### LINKED ISSUE #955: Replace slow mention queries
As recent load tests revealed, the way in which the files `frontend/utils/getProjects.ts` and `frontend/utils/editMentions.ts`, get mentions are slow. Compare e.g. the response speed of 

https://research-software-directory.org/api/v1/mention?select=*,impact_for_project!inner(*)&impact_for_project.project=eq.7a7880bd-440c-4b8d-b84c-9fda6c34adb2 

against

https://research-software-directory.org/api/v1/project?id=eq.7a7880bd-440c-4b8d-b84c-9fda6c34adb2&select=*,mention!impact_for_project(*).

And that of

https://research-software-directory.org/api/v1/mention?select=*,output_for_project!inner(*)&output_for_project.project=eq.7a7880bd-440c-4b8d-b84c-9fda6c34adb2

against

https://research-software-directory.org/api/v1/project?id=eq.7a7880bd-440c-4b8d-b84c-9fda6c34adb2&select=*,mention!output_for_project(*).

And that of

https://research-software-directory.org/api/v1/mention?select=*,mention_for_software!inner(*)&mention_for_software.software=eq.3ec00112-4abc-4f41-b9a8-0736550b8b21

against

https://research-software-directory.org/api/v1/software?id=eq.3ec00112-4abc-4f41-b9a8-0736550b8b21&select=*,mention(*)

Getting mentions starting from the software or project table is faster, so we should use those queries instead (and replace the wildcards with the columns we need).

### LINKED ISSUE #976: Improve Lighthouse score for organisation page
After recent performance improvements the Lighthouse score for software, projects and organisations overview page are significantly improved. There might be some room to improve score of organisation page (see image).

## Organisation page - software tab (current score)

image

### LINKED ISSUE #979: Software order improvements (v2)
Our new feature to order software on software overview page and on the organisation page needs further improvements;

- On the software overview page, the option `Pinned` is available. This option is only valid for organisation software and should be removed from software overview page.
image

- Default order on software overview page is on [`Mentions`](https://research-software.dev/software?order=mention_cnt).
- Should default order on organisation software page be [`Pinned`](https://research-software.dev/organisations/netherlands-escience-center?tab=software&order=is_featured&page=1&rows=24)? Now it is `Mentions`, same as on software overview page

### LINKED ISSUE #980: Participating organisation logo scaling
Logo are not scaled properly on software and project page. The object-fit type for logo's should be `contain` or maybe `scale-down`.

image

### LINKED ISSUE #982: Logos are cut in participating organizations
https://research-software.dev/projects/integrated-omics-analysis-for-small-molecule-mediated-host-microbiome-interactions
image

### PR DESCRIPTION
**Pull request by dmijatovic**
# RSD 2 release

This PR collects all features to be included in v2 release.
**include BREAKING CHANGES in the last commit. - DONE in #927**

Closes #655
Closes #789
Closes #792
Closes #803
Closes #806
Closes #823
Closes #824 
Closes #838
Closes #888
Closes #896 
Closes #916
Closes #913
Closes #924
Closes #922
Closes #932
Closes #933
Closes #934
Closes #935
Closes #936
Closes #937
Closes #938
Closes #955
Closes #976
Closes #979
Closes #980
Closes #982

Changes proposed in this pull request:
*   See separate issues   

## Conclusion
The **load tests show that RSD v2 server capacity dropped significantly compared to v1**. The additional features introduced in v2 require more resources. However, the current capacity of RSD hardware is sufficient to offer additional v2 features under the `current` traffic. After implementing few optimizations the page load of v2 is comparable to v1 when analysed using Lighthouse.

## RSD capacity difference RSD-v1.26.0 vs RSD-v2.0.0

In the K6 load test below, performed on the same hardware, we see that achieving same througoutput (100 users) with v2 is not possible. However, our current hardware CPU capacity on RSD VM seem sufficient. We utilize <10% of the hardware CPU capacity on average day. Based on this test results I expect hardware's CPU utilization to increase to ~30%. **For the partners is it important to check their current hardware utilization and take into a count required increase in capacity when upgrading to v2. The data traffic is estimated to be ~150% of v1**. Partners are adviced to test v2 performance before commiting to upgrade. 

image

## Performance improvements
Based on performed load tests on pages and the api we identified few improvement points. These are implemented in #973. **Although the performance of specific api calls is improved significantly the total server capacity remains significantly lower compared to v1 as shown in the image below**.

image

### Lighthouse audit improvements
In addition to api improvements we implemented lighthouse audit suggestions. This lead to significant improvement in the lighthouse scores especially on software overview page. The project overview page, for example, have slightly better score in v2 than in v1 (see image).

#### Software overview
image

#### Project overview
image

How to test:
* `make start` to build app
* test all functionalities specified in the separate issues

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by cmeessen** [comment]
v2 is looking great already, excellent work! I tested it using real data. Here are some unsorted remarks from my side:

### Software Highlights ordering

When adding software highlights, they are added to the end of the list and are also shown last in the software highlights view. As an admin I would expect that when I add a new software highlight, this software will be shown first on the software page.

### Image padding in cards

The new default view for software looks really good. However, many logos that were uploaded to our RSD are cropped to the content itself (no whitespace around). In the default software view, those logos touch the borders of the cards:

image

whereas others are looking amazing:

image

So, logos do not have enough padding to the boundaries whereas "illustrations" are looking good in these cards. Here are some thoughts:

- In the edit view, the uploaded images are titled "Logos". Are logos suitable to be displayed here? The GAIA entry and most other entries where not a logo was are looking really good, so maybe screenshots or illustrations are more suitable here?
- Could the user decide how the uploaded image will be displayed in this view? Maybe with a preview of the image they uploaded?

Logos are also touching the borders of the **software highlights**:

image

or, in case of illustrations, do have white space:

image

### Organisation cards

The organisation cards are looking quite empty right now. I understand that part of this is due to countries not being scraped right now, so I added the country in this example manually:

image

I've noticed that a considerable amount of space is allocated to the short descriptions. In the Helmholtz RSD, plenty of new organisations were added by the users. Almost all of them have only one software entry, and I believe that the majority will never have an organisation maintainer that could populate this field. As a result, a visitor would be looking at many empty cards in the organisation view. Also, I find it very difficult to write a short sentence about an organisation that has a very diverse field of research activities, such as universities, without sounding too generic. In conclusion, I have mixed feelings about the short description being visible in the organisation cards.

### Unverified organisations

The greyed out strikethrough checkmark for unverified organisations looks like something is wrong, and is from my point of view making a bad impression on those organisations. The icon does have a very valuable function though, i.e. contacting the admins to become a verified organisation. The vast majority of visitors seeing this button will not be the target group, so I wonder whether it would make sense to place it somewhere else. Having a contact option in the actual organisation view might be more suitable, because here the fraction of visitors that this button is relevant for, is way larger than in the organisation grid.

**Comment by jmaassen** [comment]
In the masonry layout, software entries are often duplicated. For example, "mcfly" is shown on two consecutive pages

Screenshot 2023-09-05 at 09-26-20 Software Research Software Directory

and

Screenshot 2023-09-05 at 09-26-28 Software Research Software Directory

**Comment by jmaassen** [comment]
The image area in the card is scaled to fit the logo's. Often this leads to results that do not look nice. For example: 

Not enough space on the sides, but too much above: 

Screenshot 2023-09-05 at 09-35-05 Software Research Software Directory

Screenshot 2023-09-05 at 09-39-17 Software Research Software Directory

Screenshot 2023-09-05 at 09-39-10 Software Research Software Directory

Too cramped all round: 

Screenshot 2023-09-05 at 09-45-04 Software Research Software Directory

Screenshot 2023-09-05 at 09-37-51 Software Research Software Directory

Screenshot 2023-09-05 at 09-46-34 Software Research Software Directory

Too much whitespace:

Screenshot 2023-09-05 at 09-48-15 Software Research Software Directory

Screenshot 2023-09-05 at 09-47-57 Software Research Software Directory

Logos that look good but become to big and "in your face" when scaled:

Screenshot 2023-09-05 at 09-35-33 Software Research Software Directory

Screenshot 2023-09-05 at 09-35-50 Software Research Software Directory

Screenshot 2023-09-05 at 09-36-04 Software Research Software Directory

Screenshot 2023-09-05 at 09-35-18 Software Research Software Directory

Screenshot 2023-09-05 at 09-47-44 Software Research Software Directory

Logos that don't have enough resolution to be scaled: 

Screenshot 2023-09-05 at 09-38-40 Software Research Software Directory

Screenshot 2023-09-05 at 09-38-56 Software Research Software Directory

Some examples that do work well: 

Screenshot 2023-09-05 at 09-39-24 Software Research Software Directory

Screenshot 2023-09-05 at 09-38-24 Software Research Software Directory

Screenshot 2023-09-05 at 09-38-14 Software Research Software Directory

Screenshot 2023-09-05 at 09-36-27 Software Research Software Directory

Screenshot 2023-09-05 at 09-44-51 Software Research Software Directory

Screenshot 2023-09-05 at 09-46-42 Software Research Software Directory

Screenshot 2023-09-05 at 09-44-25 Software Research Software Directory

We need to figure out how to improve this. Some random thoughts:

- More guidance for the users what works and what doesn't ?
- Use "cover images" instead of logo's, just like with projects?
- Use a fixed size image area on the tile instead of variable size?
- Use a fixed set of allowed aspect ratio's?

**Comment by jmaassen** [comment]
Small tweak (for after the release maybe?): 

There seems to be a limit of 3 keywords on the card. However, in some cases the keywords are so long they need to be put underneath each other. See AMUSE in this example:

Screenshot 2023-09-05 at 10-53-38 Software Research Software Directory

What is a bit strange here is that +2 keywords of Kernel Tuner could have easily fitted underneath the line of 3 keywords it has now. Maybe the number of keywords shouldn't be limited, but the space (= number of lines) on the card instead?

**Comment by jmaassen** [comment]
What determines the list of programming languages shown on the card?

For example OMUSE is shown like this: 

Screenshot 2023-09-05 at 11-15-52 Software Research Software Directory

However, when I look on the OMUSE page itself, it reports the following programming languages: 

Screenshot 2023-09-05 at 11-16-05 OMUSE

So C and C++ are both only 1% of the code, and PHP isn't even shown (probably part of "other"). It would make much more sense to show Fortran and Python instead (and maybe HTML), since they are the bulk of the code?

**Comment by jmaassen** [comment]
When filtering on licenses, we get a list of all licenses we see in the software. There are some entries however, (like ldot) which are commercial and do not have a specified license. Maybe we could add "unspecified" to the filter?

**Comment by jmaassen** [comment]
For after the release maybe: 

The "research domains" filter in projects can be improved a bit. As the moment the entries seems to be sorted alphabetically, which give me: 

"LS: Life Sciences" 
"LS2: Integrative Biology ..." 
"LS2_11: Bioinformatics ..." 
etc. 

The tree of categories is basically represented depth-first. As a result, the second high level category "PE: Physical Sciences ..." is a long way down the list. 

It would be more logical to show the top categories and allow more detailed to be selected when expanding? This may also link to #946 somehow?

**Comment by dmijatovic** [comment]
@cmeessen @fembau @jmaassen @ewan-escience @ctwhome I rebased this PR onto the last release of v1.27.0. **Can you test this version of PR as the first release candidate of v2.0.0, please?**

I would like to merge this PR into main as soon as possible and set it on our dev server for further testing. Before official release we want to invite some "power users" to have a look at this version before official release.  I expect official release of v2 to be ~1-2 weeks from now if no major errors are discovered.

**Review by ewan-escience — APPROVED** [review]

**Comment by dmijatovic** [comment]
@cmeessen Can you perform final test of this PR on your side. NOTE! We made one minor DB update on rpc in 100-xxx script.

```sql
-- programming language filter for software
-- used by software_overview func
CREATE FUNCTION prog_lang_filter_for_software() RETURNS TABLE (
	software UUID,
	prog_lang TEXT[]
) LANGUAGE plpgsql STABLE AS
$$
BEGIN
	RETURN QUERY
	SELECT
		repository_url.software,
		(SELECT
			ARRAY_AGG(p_lang ORDER BY repository_url.languages -> p_lang DESC)
		FROM
			JSONB_OBJECT_KEYS(repository_url.languages) p_lang
		) AS "prog_lang"
	FROM
		repository_url
	;
END
$$;
```
If you have any questions let me know :-).

**Review by cmeessen — APPROVED** [review]
Great job, I am looking forward to seeing this live!

**Pull request merged**
