### PR TITLE
More convenient frontend-dev configuration

### LINKED ISSUE #549: Frontend developer mode with docker: getaddrinfo ENOTFOUND nginx
Original post see https://github.com/hifis-net/RSD-as-a-service/issues/53

When running

```
make frontend
```

There seem to be some errors with nginx. Steps to reproduce:

1) Activate `LOCAL` in `RSD_AUTH_PROVIDERS` inside `.env` 
2) `make frontend`
3) Open http://localhost:3000
4) Click on "Sign in"
5) Use local provider
6) TYpe a name and click sign in

error message

Output in the docker log

```
hifis-frontend-dev-1  | error - Error: getaddrinfo ENOTFOUND nginx
hifis-frontend-dev-1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:84:26) {
hifis-frontend-dev-1  |   errno: -3008,
hifis-frontend-dev-1  |   code: 'ENOTFOUND',
hifis-frontend-dev-1  |   syscall: 'getaddrinfo',
hifis-frontend-dev-1  |   hostname: 'nginx'
hifis-frontend-dev-1  | }
```

The reason is that nginx configuration requires the `frontend` container to be running. However, the container is not started by the `make frontend` command.

### PR DESCRIPTION
**Pull request by cmeessen**
# Enhance docker frontend-dev configuration

Fixes #549 

Changes proposed in this pull request:

Approach number three: I would like to propose a way to run the frontend in development mode without having to build the whole `frontend` container first to save some time. This PR now adds:

**Update 3**

* substituted the `proxy_pass = http://frontend:3000` in nginx with a variable `$frontend` pointing to the same url. This trick stops nginx from checking the availability of the `frontend` container on startup, meaning it will not exit when it is not found. This way, we do not need a separate nginx image for `frontend-dev`
* use the docker resolver in nginx to discover the frontend container
* mount the nginx conf via docker-compose so the container does not have to be rebuilt every time one changes the configuration
* `frontend-dev` container creates files with same permissions as host user
* opened debugging port in `frontend-dev` to allow debugging in external tools
* update README's with instructions how to build the `frontend-dev` container without `Makefile`

**end of update 3**

This PR also fixes the issue that the `frontend-dev` container creates folder with `root` as owner. Upon building the `frontend-dev` container, the makefile will hand over the UID and GID of the user to the container, which internally creates a new user with the correpsonding IDs. That user is used to run the frontend, and accordingly the directories will have the developer's user as owner.

How to test:

* remove the root owned folders in frontend: `sudo rm -rf frontend/.next frontend/node_modules`
* start the frontend-dev container, but not the frontend container: `make frontend-docker`
* observe that the nginx container stays up running (and does not stop because http://frontend could not be found)
* open http://localhost:3000
* Local login works when `frontend` is down (no nginx error)
* `make down`
* `docker-compose up --scale scrapers=0`
* now, the frontend is available via http://localhost again

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by markusbradke** [comment]
=> ERROR [2/3] RUN addgroup --gid  frontend &&     useradd --uid 501 --gid  frontend &&     mkdir /home/frontend && chown -R frontend:frontend /home/frontend                                       0.1s
------
 > [2/3] RUN addgroup --gid  frontend &&     useradd --uid 501 --gid  frontend &&     mkdir /home/frontend && chown -R frontend:frontend /home/frontend:
#5 0.131 Value "frontend" invalid for option gid (number expected)
#5 0.131 adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
#5 0.131 [--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
#5 0.131 [--disabled-password] [--disabled-login] [--add_extra_groups] USER
#5 0.131    Add a normal user
#5 0.131
#5 0.131 adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
#5 0.131 [--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
#5 0.131 [--disabled-login] [--add_extra_groups] USER
#5 0.131    Add a system user
#5 0.131
#5 0.131 adduser --group [--gid ID] GROUP
#5 0.131 addgroup [--gid ID] GROUP
#5 0.131    Add a user group
#5 0.131
#5 0.131 addgroup --system [--gid ID] GROUP
#5 0.131    Add a system group
#5 0.131
#5 0.131 adduser USER GROUP
#5 0.131    Add an existing user to an existing group
#5 0.131
#5 0.131 general options:
#5 0.131   --quiet | -q      don't give process information to stdout
#5 0.131   --force-badname   allow usernames which do not match the
#5 0.131                     NAME_REGEX configuration variable
#5 0.131   --help | -h       usage message
#5 0.131   --version | -v    version number and copyright
#5 0.131   --conf | -c FILE  use FILE as configuration file
#5 0.131
------
executor failed running [/bin/sh -c addgroup --gid $DGID $DUNAME &&     useradd --uid $DUID --gid $DGID $DUNAME &&     mkdir /home/$DUNAME && chown -R $DUNAME:$DUNAME /home/$DUNAME]: exit code: 1
ERROR: Service 'frontend-dev' failed to build : Build failed

**Comment by markusbradke** [comment]
- GID cannot be determined with this command
- Linux command will lead to error as well --> GID 20 is already in use

**Comment by cmeessen** [comment]
@dmijatovic @ewan-escience @jmaassen I force pushed the branch with a new solution, using only one `docker-compose.yml` in the root folder. What do you think?

@markusbradke could you please check one more time? I did forget to properly escape the `$`

**Comment by markusbradke** [comment]
- looking good
- the command should be: `make dev-frontend`
- permissions are properly set

**Comment by cmeessen** [comment]
> the command should be: make dev-frontend

@markusbradke thanks for testing. `make dev-frontend` is different to `make dev-frontend-docker`. The first one runs `yarn dev` directly in the terminal. However, this does not allow to use the themes for the Helmholtz repository, because this requires folders to be mounted via `docker-compose.yml`. So we have to create a separate container that will run `yarn dev:docker`. This is why the name of the step is `dev-frontend-docker`.

**Comment by cmeessen** [comment]
@dmijatovic @ewan-escience I think now it should be good to go :)

**Comment by cmeessen** [comment]
I think it should work in every occasion now. The trick was to specify the Docker DNS as a resolver in `location /`. Ready to review.

**Review by dmijatovic — APPROVED** [review]
It works nicely!

**Pull request merged**
