### PR TITLE
888 project overview

### LINKED ISSUE #888: Project overview page v2
Upgrade project overview page to similar layout as new software overview page.

There should be two layout options: grid and list (see example)
Order and filter panel on the left side (see example)

Order (descending): Impact, Output, Start date and End date
Filters: keywords, research domains, organisation

- Icons for counts on impact and output items. (Include tooltip -> Also for software card)

## Project Card Design
image

## Example software page (grid)
image

## Example software page (list)
image

### LINKED ISSUE #896: Adjust background color for the new UI
The design's gray background color is meant to be slightly different that white. But the current color in production differs. It is a darker gray which gives more protagonism to the background. 
I would like to keep the original design and set the background color to this value: #F5F5F7
image
image

### PR DESCRIPTION
**Pull request by dmijatovic**
# Project overview page - v2

Closes #888
Closes #896 

Changes proposed in this pull request:
* Project overview page is redesigned to be in line with new software overview page
* Mouse-over message for counts included in the cards on project and software overview page
* restyled keyword "chip" in cards: smaller fonts, capitalized, one line "clamp" and bit more padding
* removed old filter components
* removed old filter RPC's from database scripts
* moved "old" software and project cards  to "components/user/.." folder. "Old" cards are still used in user and organisation sections
* changed background color
* changed avatar background color based on lighthouse contrast warning
* order on start date is descending (newest first)
* order on end date is ascending (oldest first)
* labels changed: View page, Edit page to View Project/Software, Edit Project/Software
* button "Clear" type/color changed to primary

How to test:
* `make start` to rebuild app and generate data
*  navigate to project overview page
*  test order, filters and search options
*  validate mouse over messages on the impact and output counts in the card
* login as rsd_admin to be able to edit existing project items.
* edit project images using `fit image` flag (see image 3). Try card without image too.

## Example grid view
image

## Example list view
image

## Project card image format (fit image flag)
image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests

### CODE REVIEW

**Comment by jmaassen** [comment]
Looks great! 

Some comments: 

- Sorting order of the start and end date is wrong way round? I would expect the tiles to be sorted oldest first, now it's youngest first.
- In the example dataset, one project has a long vertical image:

Screenshot 2023-06-05 at 09-39-59 Project Table white

If I toggle "Fit image to area" in the information tab I see this: 

Screenshot 2023-06-05 at 09-41-28 Edit project Research Software Directory

However, when I view the page, I see this: 

Screenshot 2023-06-05 at 09-41-54 Project Table white

so a different section of the image is used. These should either be the same, or we should allow the user to select the area (or we should simply be more strict about image ratios ;-)

**Comment by ewan-escience** [comment]
When there are zero impact or output items, the hover doesn't show up, is that intentional? And why isn't the masonry layout available for projects? 

I would expect the youngest projects to be shown first by the way. 😉 But maybe we should add an option to sort either ascending or descending.

**Comment by jmaassen** [comment]
The image fitting rules seem a bit strange to me. For example these two projects use the same image: 

Screenshot 2023-06-05 at 09-53-37 Projects Research Software Directory

The one with the smaller image has "Fit image into the area" switched on, while the one that fills the area has it switched off. It's not clear to my why the smaller image has a border all around? Shouldn't it zoom until it either hits the height or the width of the image? 

Also: the name of the switch is a bit ambiguous. Maybe rename into something like "zoom image to fill area?"

**Comment by ctwhome** [comment]
Great work in such a short time! 

looking at the result, I think the progress bar should be (in the end) at the bottom of the card, rather than underneath the photo. I find it because the bar blends into the image of the project and it looks somehow out of place. Another important reason is that the progress bar will be closer to the context of the start date and end date. 

This is how it could lf the bar is moved to the bottom of the card and the other options:
image

**Comment by jmaassen** [comment]
As an alternative to the progress bar we could also use a percentage?

**Comment by dmijatovic** [comment]
@jmaassen @ctwhome @ewan-escience Thanks for the feedback. All issues are addressed and discussed during the standup this morning. Can one of you validate all changes are implemented. If you want to restore real data I did "upgraded" posted backup in Teams yesterday.

**Review by ctwhome — APPROVED** [review]

**Review by ewan-escience — APPROVED** [review]

**Pull request merged**
