### PR TITLE
Setup end to end tests

### LINKED ISSUE #674: Create e2e test setup
Create initial setup for e2e with Playwright

### PR DESCRIPTION
**Pull request by dmijatovic**
# Setup end to end tests

Closes #674 

Changes proposed in this pull request:
*  setup end to end tests for RSD using Playwright framework
*  setup github action triggers for all tests, e2e tests will run on PR and merge to main, it uses e2e/.env.e2e file with "fake" secrets
*  renamed `make down` to `make stop`    
*  renamed testing github actions
*  removed unit test from frontend build process
*  created `make e2e-tests` to run tests locally

How to test:
* `make e2e-tests` to run e2e tests locally
*  e2e tests should also run on each PR, so this PR should also run e2e tests :-)

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by jmaassen** [comment]
Works okay, although I did have 2 test failing with a timeout: 

```
tests_1  | 
tests_1  | > rsd-dev@1.0.0 e2e:all
tests_1  | > playwright test
tests_1  | 
tests_1  | 
tests_1  | Running 18 tests using 6 workers
tests_1  | 
             1) [webkit] › software.spec.ts:39:1 › Edit software info =========================================
tests_1  | 
tests_1  |     Test timeout of 30000ms exceeded while tearing down "context".
tests_1  | 
tests_1  |     Retry #1 ---------------------------------------------------------------------------------------
tests_1  | 
tests_1  |     Test timeout of 30000ms exceeded.
tests_1  | 
tests_1  |     Pending operations:
tests_1  |       - locator.click at tests/software.spec.ts:60:18
tests_1  | 
tests_1  | 
tests_1  |     attachment #1: trace (application/zip) ---------------------------------------------------------
tests_1  |     test-results/software-Edit-software-info-webkit-retry1/trace.zip
tests_1  |     Usage:
tests_1  | 
tests_1  |         npx playwright show-trace test-results/software-Edit-software-info-webkit-retry1/trace.zip
tests_1  | 
tests_1  |     ------------------------------------------------------------------------------------------------
tests_1  | 
             2) [webkit] › project.spec.ts:34:1 › Edit project info ===========================================
tests_1  | 
tests_1  |     Test timeout of 30000ms exceeded.
tests_1  | 
tests_1  |     locator.click: Target closed
tests_1  |     =========================== logs ===========================
tests_1  |     waiting for getByRole('button', { name: 'Save' })
tests_1  |       locator resolved to visible <button tabindex="0" type="submit" id="save-button" form…>…</button>
tests_1  |     attempting click action
tests_1  |       waiting for element to be visible, enabled and stable
tests_1  |     ============================================================
tests_1  | 
tests_1  |        at ../helpers/project.ts:138
tests_1  | 
tests_1  |       136 |   await Promise.all([
tests_1  |       137 |     // click on save
tests_1  |     > 138 |     saveBtn.click(),
tests_1  |           |             ^
tests_1  |       139 |     // it should make request to /url_for_project
tests_1  |       140 |     page.waitForResponse(/\/url_for_project/)
tests_1  |       141 |   ])
tests_1  | 
tests_1  |         at createProjectLink (/app/helpers/project.ts:138:13)
tests_1  |         at /app/tests/project.spec.ts:54:5
tests_1  | 
tests_1  |     Pending operations:
tests_1  |       - locator.click at helpers/project.ts:125:13
tests_1  | 
tests_1  | 
tests_1  |     attachment #1: trace (application/zip) ---------------------------------------------------------
tests_1  |     test-results/project-Edit-project-info-webkit/trace.zip
tests_1  |     Usage:
tests_1  | 
tests_1  |         npx playwright show-trace test-results/project-Edit-project-info-webkit/trace.zip
tests_1  | 
tests_1  |     ------------------------------------------------------------------------------------------------
tests_1  | 
             Slow test file: [webkit] › project.spec.ts (2m)
tests_1  |   Slow test file: [webkit] › software.spec.ts (1m)
tests_1  |   Slow test file: [firefox] › project.spec.ts (57s)
tests_1  |   Slow test file: [firefox] › software.spec.ts (54s)
tests_1  |   Slow test file: [chromium] › project.spec.ts (48s)
tests_1  |   Consider splitting slow test files to speed up parallel execution
tests_1  | 
tests_1  |   1 failed
tests_1  |     [webkit] › software.spec.ts:39:1 › Edit software info ==========================================
tests_1  |   1 flaky
tests_1  |     [webkit] › project.spec.ts:34:1 › Edit project info ============================================
tests_1  |   1 skipped
tests_1  |   15 passed (2m)
tests_1  | 
tests_1  | To open last HTML report run:
tests_1  | 
tests_1  |   npx playwright show-report
tests_1  | 
rsd_tests_1 exited with code 1
```

**Comment by dmijatovic** [comment]
@jmaassen Yes, testing webkit on ubuntu seem not to be optimal. I had similar timeout issues. I think testing webkit/safari should be done on mac os. This is possible to setup in the Github action and has my preference. 

For local e2e testing we could focus on one browser that performs test well on all platforms (chrome) in the default script `make e2e-tests`. I created separate npm scripts to run e2e tests in chromium, firefox and webkit separately, so when one needs additional testings these scripts could be used. 

The "main" validation will be performed by github action and there we can create more realistic scenario and run the test on "native" browser platforms. The ideal "martix" in my opinion would be:
 - chrome and firefox on ubuntu
 - safari and chrome on mac-os
 - chrome, firefox and edge on windows (if there is windows image with docker-compose available in github actions)

**Comment by cmeessen** [comment]
I tested in on Manjaro, running `make e2e-tests`. This is the output I received:

```
ttaching to e2e-tests-1
e2e-tests-1  | 
e2e-tests-1  | > rsd-dev@1.0.0 e2e:docker
e2e-tests-1  | > playwright test --project=chrome --project=firefox --project=msedge
e2e-tests-1  | 
e2e-tests-1  | 
e2e-tests-1  | Running 24 tests using 6 workers
e2e-tests-1  | 
               locator.click: Timeout 30000ms exceeded.
e2e-tests-1  | =========================== logs ===========================
e2e-tests-1  | waiting for getByRole('button', { name: 'Decline' })
e2e-tests-1  | ============================================================
e2e-tests-1  | 
e2e-tests-1  |    at ../helpers/globalSetup.ts:47
e2e-tests-1  | 
e2e-tests-1  |   45 |   await page.getByRole('button', {
e2e-tests-1  |   46 |     name: 'Decline'
e2e-tests-1  | > 47 |   }).click()
e2e-tests-1  |      |      ^
e2e-tests-1  |   48 |   // sign in - we need to do this because we loose cookies
e2e-tests-1  |   49 |   await loginLocal({
e2e-tests-1  |   50 |     page,
e2e-tests-1  | 
e2e-tests-1  |     at globalSetup (/app/helpers/globalSetup.ts:47:6)
e2e-tests-1  | 

e2e-tests-1  |   24 skipped
e2e-tests-1  |   1 error was not a part of any test, see above for details
e2e-tests-1  | 
e2e-tests-1  | To open last HTML report run:
e2e-tests-1  | 
e2e-tests-1  |   npx playwright show-report
e2e-tests-1  | 
e2e-tests-1 exited with code 1
```

Then container has been removed, so unfortunately I cannot have a look at the report.

**Comment by cmeessen** [comment]
After adding Matomo parameters to `.env`, the tests finished successfully :+1: The reports also work.

**Comment by jmaassen** [comment]
I'm getting a few timeouts:

```
Attaching to rsd_tests_1
tests_1  | 
tests_1  | > rsd-dev@1.0.0 e2e:docker
tests_1  | > playwright test --project=chrome --project=firefox --project=msedge
tests_1  | 
tests_1  | 
tests_1  | Running 24 tests using 6 workers
tests_1  | 
             1) [msedge] › project.spec.ts:57:3 › Project › Edit project info =================================
tests_1  | 
tests_1  |     Test timeout of 30000ms exceeded while tearing down "context".
tests_1  | 
             2) [firefox] › software.spec.ts:69:3 › Software › Edit software info =============================
tests_1  | 
tests_1  |     Test timeout of 30000ms exceeded.
tests_1  | 
tests_1  |     Pending operations:
tests_1  |       - locator.click at tests/software.spec.ts:90:20
tests_1  | 
tests_1  | 
tests_1  |     attachment #1: trace (application/zip) ---------------------------------------------------------
tests_1  |     test-results/software-Software-Edit-software-info-firefox/trace.zip
tests_1  |     Usage:
tests_1  | 
tests_1  |         npx playwright show-trace test-results/software-Software-Edit-software-info-firefox/trace.zip
tests_1  | 
tests_1  |     ------------------------------------------------------------------------------------------------
tests_1  | 
             3) [firefox] › project.spec.ts:57:3 › Project › Edit project info ================================
tests_1  | 
tests_1  |     Test timeout of 30000ms exceeded.
tests_1  | 
tests_1  |     Pending operations:
tests_1  |       - locator.click at helpers/project.ts:181:6
tests_1  | 
tests_1  | 
tests_1  |     attachment #1: trace (application/zip) ---------------------------------------------------------
tests_1  |     test-results/project-Project-Edit-project-info-firefox/trace.zip
tests_1  |     Usage:
tests_1  | 
tests_1  |         npx playwright show-trace test-results/project-Project-Edit-project-info-firefox/trace.zip
tests_1  | 
tests_1  |     ------------------------------------------------------------------------------------------------
tests_1  | 
             Slow test file: [firefox] › project.spec.ts (2m)
tests_1  |   Slow test file: [firefox] › software.spec.ts (2m)
tests_1  |   Slow test file: [msedge] › project.spec.ts (2m)
tests_1  |   Slow test file: [chrome] › project.spec.ts (1m)
tests_1  |   Slow test file: [msedge] › software.spec.ts (60s)
tests_1  |   Consider splitting slow test files to speed up parallel execution
tests_1  | 
tests_1  |   3 flaky
tests_1  |     [firefox] › project.spec.ts:57:3 › Project › Edit project info =================================
tests_1  |     [firefox] › software.spec.ts:69:3 › Software › Edit software info ==============================
tests_1  |     [msedge] › project.spec.ts:57:3 › Project › Edit project info ==================================
tests_1  |   21 passed (2m)
tests_1  | 
tests_1  | To open last HTML report run:
tests_1  | 
tests_1  |   npx playwright show-report
tests_1  | 
rsd_tests_1 exited with code 0
```

**Review by ewan-escience — APPROVED** [review]

**Pull request merged**
