### PR TITLE
rsd admin can edit package manager item

### LINKED ISSUE #1277: Package manager admin messaging
We could improve ui for admins for disabling package manager scrapers.

image

### PR DESCRIPTION
**Pull request by dmijatovic**
# Rsd admin can edit package manager item

Closes #1277

Changes proposed in this pull request:
* Rsd admin can edit package manager item. It can: 
    * disable service by adding a comment into designated input field. The input is enabled only for the services that are "supported". **The info about "supported services" is kept locally (in an data object) and need to be manually updated.**
    * change "detected platform" using a drop-down options. The list of supported providers is kept locally (in same data object) and need to be manually updated. 
* When updating package manager entry only platform and the reasons for disabling are updated

How to test:
* `make start` to build app and create test data
* login as rsd_admin, first user should become rsd_admin automatically if you have correct .env settings
* open first software item and navigate to package managers section
* confirm you can edit existing item
* confirm you can provide reason to stop scraping
* confirm that disabling is visible on the PackMan page
* confirm that disabling is visible on the background services page
* confirm you can create new item
* login as regular rsd user
* edit or create software item
* navigate to package manager section
* confirm you cannot edit package manager item
* confirm you can delete and add new items

## Add package manager (not changed)
image

## Admin package manager modal (to disable service or change platform)
image

## Example disabled service on PM page
image

## Example disabled service on services page
image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by jmaassen** [comment]
Setting the message works well, and the difference between admin and regular user is as expected. 

However, when I set the message as an admin, I don't see any visual feedback on this as a user in the package manager section (only in the 'background services section'). An improvement would be to add some icon or message indicating a error, that links to the background services section?

**Review by jmaassen — APPROVED** [review]
Works as expected.

**Review by ewan-escience — CHANGES_REQUESTED** [review]
When the PATCH request is sent, all the data is sent, but that should only be the data in the form.

When the URL is changed, the counts are not reset to `null`. I actually don't think it should be possible to change the URL (instead delete the entry and create a new one).

**Comment by jmaassen** [comment]
Works well. 

Small comment: 

Screenshot 2024-08-23 at 09-38-39 Edit software Research Software Directory

Instead of saying "Why ... is disabled?" it may be better to say "Reason to disable ...."

**Review by ewan-escience — CHANGES_REQUESTED** [review]
Nice work, I have two small issues left:

1. The `id` is still sent in the PATCH request
2. When opening the edit modal, the `Detected platform` field always shows the detected platform, not the platform saved in the database, which is a bit confusing. I would rename it to just `Platform` and show the saved platform (maybe also showing the detected platform separately).

**Review by ewan-escience — APPROVED** [review]

**Pull request merged**
