### PR TITLE
feat: edit software and project mention pages

### LINKED ISSUE #1076: Enable citation scrapers for project output items
We introduced new mention scraper feature in software that will look for the citations of the reference papers. We could implement similar approach that automatically scrapes all citations of the project output papers and add these to project impact section. Currently the impact items are added manually by project maintainers.

### LINKED ISSUE #1121: Edit software mentions section
Based on the changes performed in #1115 for the project pages we want to "streamline" the edit software mentions section. Currently there are 2 mention options: reference papers and mentions. We decided to make one menu option "mentions" with 3 tabs: reference papers, citations and related output.

### PR DESCRIPTION
**Pull request by dmijatovic**
# Edit software and project mentions pages

Closes #1121
Closes #1076
Closes #1115 

Changes proposed in this pull request:
* One menu options "Mentions" instead of two (mentions and reference papers)
* Three tabs on the page: reference papers, citations, related output    
* This PR includes both software and project mentions!

How to test:
* `make start` to build and generate test data
* login as rsd_admin, create new software or edit existing
* add reference papers:
  * doi:10.1186/s13321-017-0220-4
  * 10.1186/1758-2946-6-3
  * https://doi.org/10.1021/ja026939x
* add, import, create related output
   * for import use the list [from this issue](https://github.com/research-software-directory/RSD-as-a-service/pull/808)
* validate citations are scraped (ensure scrapers are running in dev)
* create new project or edit existing project
* add output and impact items manually
* observe the scrapers generating citations based on the items added to output
* test adding manual items and import

## Edit software mentions
image

## Edit project mentions
image

PR Checklist:

*   [x] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests

### CODE REVIEW

**Comment by jmaassen** [comment]
Some text improvements for the software mentions: 

At reference papers: 

"Here you can add reference papers which describe your software. The RSD will periodically look for citations of these papers using OpenAlex and add them to the citations list on this page."

At citations: 

"Here we list all the citations of your reference papers that the RSD was able to find automatically. On the software page these citations are shown in the mentions section together with any items you have manually added in the related output section."

At related output: 

"Here you can add research output related to your software that cannot be found automatically by the RSD, such as publications that do not cite your software or reference papers directly, presentations, blogs, tutorials, news articles, videos, policy documents, etc."

**Comment by jmaassen** [comment]
The deduplication between reference papers and scraped mentions isn't 100% correct yet. For example, "Kernel Tuner" has the following reference papers: 

10.1109/tevc.2022.3210654
10.1016/j.future.2018.08.004
10.1109/pmbs54543.2021.00017
10.1109/pmbs56514.2022.00010

After the scrapers have run, there are 49 citations found.  However, these also include (at least) these two papers:

10.1109/pmbs54543.2021.00017
10.1109/pmbs56514.2022.00010

So these show up twice in the final software page, once in reference papers and once in mentions

**Comment by cmeessen** [comment]
I think the UI reduction is a good step forward to make using the RSD more intuitive :+1: I could imagine that some users may be confused because the reference papers item is not appearing in the sidebar anymore. Would it make sense to add a notification somehow? Maybe a news item would be helpful too, but I think this is still WIP?

**Review by ewan-escience — APPROVED** [review]
Switching away from a tab with ~200 items is a tad slow, but otherwise it seems to work well.

**Comment by jmaassen** [comment]
More text changes: 

For software/reference papers:

"Here you can add reference papers that describe your software. The RSD will periodically look for citations of these papers using OpenAlex and add them to the citations list on this page."

On software/related output:

"Here you can add research output related to your software that cannot be found automatically by the RSD, such as papers, presentations, blogs, tutorials, news articles, videos, policy documents, etc. On the software page this output is shown in the mentions section together with citations that have been found automatically."

Also on software/related output:

"No mentions to show" -> "No related output to show"

**Comment by jmaassen** [comment]
On projects/citations:

"these citations are showed in" -> "these citations are shown in"

**Comment by dmijatovic** [comment]
@jmaassen, @ewan-escience, @cmeessen I have refactored mention section in order to improve user experience during tab switch. In this version we only load first 50 items per group in order to speed up loading. Can you please review this version?

**Review by jmaassen — APPROVED** [review]
Works well from a users perspective.

**Review by cmeessen — APPROVED** [review]

**Pull request merged**
