### PR TITLE
Imperial home page

### PR DESCRIPTION
**Pull request by cc-a**
# Pull request Title

Based on the initial template provided by @dmijatovic this PR implements a customised landing page for Imperial College. 

Changes proposed in this pull request:

* For the most part changes are self contained in `frontend/components/home/imperial`. The home page is quite simple, providing buttons linking to `/software` and `/software/add` as well as displaying the most popular keywords associated with software packages and various counts from the database.
* In order to support displaying distinct counts for open and closed source software packages an entry for `open_source_cnt` was added to the `homepage_counts` rpc function and associated datastructes within the frontend.

How to test:

* Download [imperial.tar.gz](https://github.com/research-software-directory/RSD-as-a-service/files/12314911/imperial.tar.gz) and extract it in `deployment`.
* Create a `docker-compose.override.yml` with the following contents:
```yaml
version: "3.0"
services:
  frontend-dev:
    volumes:
      - ./deployment/imperial/styles:/app/public/styles
      - ./deployment/imperial/data:/app/public/data
      - ./deployment/imperial/images:/app/public/images
```
* Run `docker compose build database` and `docker compose down -v` to get a clean version of the database with updates.
* Run `make frontend-docker` and access `http://localhost:3000`

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

Closes https://github.com/ImperialCollegeLondon/RSD-as-a-service/issues/10

### CODE REVIEW

**Comment by ewan-escience** [comment]
Looks good to me, two things:

- I'd rather have probability 0.2 for generating closes source software, as this better aligns with what we have.
- When I'm not logged in, the Submit Software button hard links to SURFconext, but when I click the Sign in button instead, I get to choose a provider.

**Comment by ewan-escience** [comment]
About the second point, I get messages from the frontend that AZURE is not supported for logging in, which might cause the hard link to SURFconext. Maybe rebasing on main will resolve that.

**Review by dmijatovic — APPROVED** [review]
Nice work! I have 3 suggestions concerning the theme colors. I will post them in the separate thread

**Comment by dmijatovic** [comment]
@cc-a Conerning the theme colors values in the settings.json. There are 3 improvements, 2 concerning the dark theme and one for light theme. The dark theme colors are used on the software and project pages in the "contrast" sections (citations, mentions, impact and output).

## Lines between mention groups on software page and impact/output on project page.
The line color is defined in settings.json prop `theme.dark.colors.base-300`. I used `#D0DBE6` in the example below

image


## Background color of dropdown boxes in citation section of software page.
The background color is defined in settings.json prop `theme.dark.colors.base-100`. I used `#006EAF` in the example below

image

## Hover color on organisation cards
This color is defined in settings.json prop `theme.light.colors.accent`. The current color does not have sufficient contract in my opinion.

image


**As these changes are not related to code but to values in the settings.json I approved this PR and will be merging it shortly. OK?**

I also want to make you aware about significant changes we are introducing in v2 for software, project and organisation overview pages (demo can be seen on out dev server)[https://research-software.dev/software?order=mention_cnt]. We plan to release new version in September 2023 and merge it into main. For this purpose we created PR #787 that collects all v2 changes. We would also want someone from your team to check this PR when it is ready to be merged into main.

**Comment by dmijatovic** [comment]
@cc-a I would like to merge this PR into main. Is that OK with you?

**Comment by cc-a** [comment]
@dmijatovic apologies for the lack of responsiveness and I appreciate you pushing forward with things. I've been involved in organising the UK RSE conference and my wife has had a bought of covid. I'll review the settings and get those updated. Thanks again!

**Pull request merged**
