### PR TITLE
feat: programming languages GitHub scraper

### LINKED ISSUE #90: Programming languages scraper
Write a scraper that scrapes the programing languages used by a software tool from its repository.

### PR DESCRIPTION
**Pull request by ewan-escience**
# Programming languages GitHub scraper

Changes proposed in this pull request:

* Add a scraper that scrapes the GitHub API to collect the programming languages used in repositories. It runs a cron job in a Docker container that runs every 6 minutes. The amount of requests is makes is configurable and it supports using a GitHub authentication token to increase the rate limit. 

How to test:

Since the database structure has changed, we have to delete and build everything
* Copy the new version of the file `frontend/.env.local.example` to `frontend/.env.production.local`
* Optionally fill in the new values
* Dont't forget to fill in the existing secrets again
* `docker-compose down --volumes`
* `docker-compose build`
* `docker-compose up`
* Every six minutes, you should see that the amount of data on https://localhost/api/v1/programming_languages has increased. 
* Repositories without data will be scraped first, then in order of last updated.

PR Checklist:

*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

Closes #90

### CODE REVIEW

**Comment by ewan-escience** [comment]
By the way, some effort should be put into investigating if using GitHub's GraphQL is a better alternative than using the REST API. Now we have to make a HTTP request for every repo we want to scrape its programming languages for, which is slow. Maybe with GraphQL we can do that in a single query.

**Comment by ctwhome** [comment]
if that would widen the API requests why not? GraphQL is awesome btw

**Review by dmijatovic — APPROVED** [review]
Nice job! I tested it and it works as intended.

**Review by jmaassen — APPROVED** [review]
Works like a charm once the Legacy RSD was up again ;-)

**Pull request merged**
