### PR TITLE
Landing page content updates

### LINKED ISSUE #629: Home page and text updates
Update home page based on adapted Figma design and some additional text correction

Homepage

### PR DESCRIPTION
**Pull request by ctwhome**
Fixes #629 

Changes proposed in this pull request:

*  Add get started, our goals, about and learn more sections
*  changes to previous text according to the design
*  Add animated entries to several elements
*  Links used on homepage:
   *  Discover Software: /software
   *  Add your Software: https://research-software-directory.github.io/documentation/adding-software.html
   *  Register your organization: mailto:rsd@esciencecenter.nl?subject=Register organisation
   *  About us: /about (exists on rsd production)
   *  Docs: https://research-software-directory.github.io/documentation/
   *  FAQ: /faq (DOES NOT EXISTS YET)
   *  Contact us: mailto:rsd@esciencecenter.nl?subject=Question about RSD
   *  Meet out team: https://www.esciencecenter.nl/research-software-directory/
   *  Join us on Github: https://github.com/research-software-directory/RSD-as-a-service

#### How to test:

* `make start`
* read all text and validate all links/buttons

## Example implementation
image

image

image

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Comment by ctwhome** [comment]
@dmijatovic all the visual elements are now implemented, or they should. Could you finish the PR when the pages for the buttons have been created?

It looks like the build gives an error: in my case with the sharp library, which it seems we are not using anywhere?

```javascript
> Build error occurred
[Error: ENOENT: no such file or directory, copyfile '/Users/ctw/Sites/github/escience/rsd/RSD-as-a-service/frontend/node_modules/sharp/build/Release/sharp-darwin-x64.node' -> '/Users/ctw/Sites/github/escience/rsd/RSD-as-a-service/frontend/.next/standalone/node_modules/sharp/build/Release/sharp-darwin-x64.node'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/Users/ctw/Sites/github/escience/rsd/RSD-as-a-service/frontend/node_modules/sharp/build/Release/sharp-darwin-x64.node',
  dest: '/Users/ctw/Sites/github/escience/rsd/RSD-as-a-service/frontend/.next/standalone/node_modules/sharp/build/Release/sharp-darwin-x64.node'
}
error Command failed with exit code 1.

```

Thank you

**Comment by dmijatovic** [comment]
@jmaassen @ctwhome @ewan-escience Do we want links under the buttons, which are not defined because documentation pages are not created yet, to be part of the settings?

**Review by cmeessen — APPROVED** [review]

**Comment by jmaassen** [comment]
Great that the search now also works on partial strings!

The top bar now says "Search or jump to..." maybe it would be better to use "Search in RSD" or "Search all" ? This would make the scope of the search clear, and set it apart from the "Find software / project / organization" in the lower bar.

**Comment by dmijatovic** [comment]
> Great that the search now also works on partial strings!
> 
> The top bar now says "Search or jump to..." maybe it would be better to use "Search in RSD" or "Search all" ? This would make the scope of the search clear, and set it apart from the "Find software / project / organization" in the lower bar.

Maybe we can call it "Search in RSD or jump to...". We still have "jump to" option that might be worth of mentioning

**Pull request merged**
