### PR TITLE
chore: exclude test and mock files from sonar code analyses

### PR DESCRIPTION
**Pull request by dmijatovic**
# Exclude folders and files from Sonar analyses

Changes proposed in this pull request:
* Do not analyse test, mocks and assets folders
* Define all test files   

How to test:
* De sonar analyses should now exclude large number of irrelevant files from it's analyses.

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [ ] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by ewan-escience — CHANGES_REQUESTED** [review]
You need to use `sonar.coverage.exclusions` instead of `sonar.exclusions`, see the section `Refined scope settings` on https://docs.sonarcloud.io/advanced-setup/analysis-scope/.

**Comment by dmijatovic** [comment]
> You need to use `sonar.coverage.exclusions` instead of `sonar.exclusions`, see the section `Refined scope settings` on https://docs.sonarcloud.io/advanced-setup/analysis-scope/.

Yes, I saw that. The exclusion I defined is not only for coverage but for all sonar analyses. These folders should folders should be excluded from Sonar analyses completely not only for the coverage. 

For the coverage to be identical to local Jest  report we would need to use inclusion option but that option does not exists in Sonar for the coverage. I am accepting that there will be some difference :-(. I expect if the test files are defined properly the stats will improve. From there we can decide on next steps.

**Review by ewan-escience — CHANGES_REQUESTED** [review]
On the same page, it says

> The test scope parameters (source.tests , sonar.test.exclusion, and sonar.test.inclusion) do not have anything to do with setting up test coverage reporting (see [Test Coverage](https://docs.sonarcloud.io/enriching/test-coverage/overview/)).

So you will not get the desired result this way. It will be worse, because the test code should be analysed but not be in the test coverage.

**Review by ewan-escience — APPROVED** [review]
Let's see if it works...

**Pull request merged**
