### PR TITLE
770 extra git data

### LINKED ISSUE #770: Scrape extra data from Git repositories
We want to scrape the number of stars, forks, open issue count, contributors and maybe more from Git repositories. 

- On GitHub, we can easily get them from e.g. https://api.github.com/repos/research-software-directory/RSD-as-a-service, search for `stargazers_count`, `forks_count`, `open_issues_count` and visit https://api.github.com/repos/research-software-directory/RSD-as-a-service/contributors for the contributors.
- On GitLab, it does not seem possible to get the counts, but we can get the [contributors](https://docs.gitlab.com/ee/api/repositories.html#contributors).

### PR DESCRIPTION
**Pull request by ewan-escience**
# Scrape more Git data

Changes proposed in this pull request:

* Add a scraper that scrapes for GitHub and GitLab the star count, fork count and open issue count (GitHub only), the license scraper is merged into this scraper
* Add a scraper that scrapes for GitHub and GitLab the contributor count
* Some refactoring and renaming of the scrapers

How to test:
* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=1`.
* Wait for all the scrapers to run or run all Git scrapers with the following commands:
```bash
docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainProgrammingLanguages
docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainContributors
docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainBasicData
docker-compose exec scrapers java -cp /usr/myjava/scrapers.jar nl.esciencecenter.rsd.scraper.git.MainCommits
```
Use a tool like DBeaver to check that data for all categories have been scraped (`SELECT * FROM repository_url;`)

Closes #770

PR Checklist:

*   [X] Increase version numbers in `docker-compose.yml`
*   [X] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

**Review by dmijatovic — APPROVED** [review]
Works as described

**Comment by cmeessen** [comment]
When I create a new software and add a GitLab URL the frontend throws an error:

image

Steps to reproduce:

* create new software
* add repository url `https://codebase.helmholtz.cloud/hifis/overall/hifis.net`
* Change the focus away from the text field => error message shows
* Change Platform to GitLab => error still shows

**Review by cmeessen — CHANGES_REQUESTED** [review]
I could not find a way to make the frontend store the repository URL of a gitlab repo.

**Comment by ewan-escience** [comment]
Good catch @cmeessen! I changed the frontend, can you try it again?

**Review by cmeessen — APPROVED** [review]

**Comment by cmeessen** [comment]
Looking good, stars, forks and contributors are being scraped.

**Pull request merged**
